Repository cilium/tetragon, pull requests merged in 2023-04, with the labels that each got.

#880 Makefile: set `GOARCH` to `TARGET_ARCH` only if `GOARCH` is unset
  Makefile
Labels: bug, area/ci, arch/arm64

#886 TracingPolicy examples: use portable symbols for syscalls
  examples/tracingpolicy/fd_memfd_kill.yaml
  examples/tracingpolicy/hardlink-observe.yaml
  examples/tracingpolicy/hardlink-override.yaml
  examples/tracingpolicy/match_capability_changes.yaml
  examples/tracingpolicy/match_namespace_changes.yaml
  examples/tracingpolicy/names.yaml
  examples/tracingpolicy/open_kill.yaml
  examples/tracingpolicy/symlink-observe.yaml
  examples/tracingpolicy/symlink-override.yaml
  examples/tracingpolicy/sys_clock_settime.yaml
  examples/tracingpolicy/sys_mount.yaml
  examples/tracingpolicy/sys_pivot_root.yaml
  examples/tracingpolicy/sys_ptrace.yaml
  examples/tracingpolicy/sys_setuid.yaml
  examples/tracingpolicy/sys_write_follow_fd_etc_pwd.yaml
  examples/tracingpolicy/sys_write_follow_fd_prefix.yaml
  examples/tracingpolicy/sys_write_sigkill.yaml
  examples/tracingpolicy/write.yaml
Labels: arch/arm64

#883 Tetra: split commands set between OS for portability
  cmd/tetra/commands.go
  cmd/tetra/commands_darwin.go
  cmd/tetra/commands_linux_dynamic.go
  cmd/tetra/commands_linux_static.go
  cmd/tetra/commands_windows.go
  cmd/tetra/full_commands.go
  cmd/tetra/standalone_commands.go
Labels: kind/bug

#913 Backports/v0.9: Tetra: split commands set between OS for portability
  cmd/tetra/commands.go
  cmd/tetra/commands_darwin.go
  cmd/tetra/commands_linux_dynamic.go
  cmd/tetra/commands_linux_static.go
  cmd/tetra/commands_windows.go
  cmd/tetra/full_commands.go
  cmd/tetra/standalone_commands.go
Labels: kind/backport

#912 Backports/v0.9: Makefile: set GOARCH to TARGET_ARCH only if GOARCH is unset
  Makefile
Labels: kind/backport

#938 tetragon: deal with duplicated tcpmon_map issue
  cmd/tetragon/main.go
  pkg/bench/bench.go
  pkg/observer/observer.go
  pkg/observer/observer_test_helper.go
  pkg/sensors/manager.go
  pkg/sensors/manager_test.go
  pkg/testutils/sensors/sensors.go
Labels: needs-backport/0.9

#948 tetragon: Add documentation for Signal and NoPost actions
  docs/content/en/docs/reference/tracing-policy.md
Labels: area/documentation

#898 bug-report-template: add an issue template for bug report
  .github/ISSUE_TEMPLATE/bug_report_template.yaml
Labels: kind/enhancement
