Repository cilium/tetragon, pull requests merged in 2023-01, with the labels that each got.

#609 eventcache: update PodInfoError on pod error
  pkg/eventcache/eventcache.go
Labels: needs-backport/0.8

#632 Minor improvements to the README
  README.md
Labels: area/documentation

#644 e2e-framework: force update when adding helm repo
  tests/e2e/install/tetragon/tetragon.go
Labels: backport-pending/0.8

#659 ci: pin docker buildx version to v0.9.1
  .github/workflows/build-clang-image.yaml
  .github/workflows/build-images-ci.yml
  .github/workflows/build-images-releases.yml
Labels: needs-backport/0.8

#661 pkg/config: add k8s validation on `metadata.name`
  pkg/bench/trace_bench_open.go
  pkg/bench/trace_bench_rw.go
  pkg/config/yaml.go
  pkg/config/yaml_test.go
  pkg/sensors/tracing/kprobe_test.go
  testdata/specs/capchanges.yaml.tmpl
  testdata/specs/nschanges.yaml.tmpl
  testdata/specs/sigkill_unprivileged_user_namespace.yaml.tmpl
  testdata/specs/sigkill_unprivileged_user_namespace_in_pid_namespace.yaml.tmpl
Labels: bug, go

#670 pkg/config: print name in validation error
  pkg/config/yaml.go
Labels: enhancement, go
