Repository cilium/tetragon, pull requests merged in 2023-08, with the labels that each got.

#1300 workflows: split static checks to parallelize jobs
  .github/workflows/static-checks.yaml
Labels: area/ci

#1276 sensors: harden string parsing from BPF events
  pkg/sensors/tracing/generickprobe.go
  pkg/sensors/tracing/generickprobe_test.go
Labels: area/userspace

#1322 Revert "renovate: fix usage of dot in regexes"
  .github/renovate.json5
Labels: area/ci

#1367 tracing: multiple action fixes
  bpf/process/types/basic.h
  pkg/selectors/kernel.go
  pkg/selectors/kernel_test.go
Labels: release-note/bug, needs-backport/0.10

#1377 docs: split Tracing Policy concept page into subpages
  docs/assets/scss/page-info.scss
  docs/content/en/docs/concepts/k8s-filtering.md
  docs/content/en/docs/concepts/tracing-policy/_index.md
  docs/content/en/docs/concepts/tracing-policy/example.md
  docs/content/en/docs/concepts/tracing-policy/hooks.md
  docs/content/en/docs/concepts/tracing-policy/selectors.md
  docs/content/en/docs/getting-started/try-tetragon-linux.md
Labels: area/documentation

#1384 gha: add pr-validation GH action
  .github/workflows/pr-validation.yaml
Labels: release-note/ci

#1398 process.GetPodInfo: Don't return Cilium endpoint
  pkg/grpc/exec/exec.go
  pkg/grpc/process_manager_test.go
  pkg/process/podinfo.go
  pkg/process/podinfo_test.go
  pkg/process/process.go
Labels: release-note/misc

#1402 cmd/tetra: retry failed gRPC connections with exponential backoff
  cmd/tetra/common/client.go
  cmd/tetra/common/flags.go
  cmd/tetra/main.go
Labels: release-note/minor

#1369 Add Registration logic for Pod Info Custom Resource Definition.
  install/kubernetes/templates/clusterrole.yaml
  install/kubernetes/templates/operator_clusterrole.yaml
  operator/crd/crd.go
  operator/flags.go
  operator/option/config.go
  pkg/k8s/Makefile
  pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_podinfo.yaml
  pkg/k8s/apis/cilium.io/client/register_v1_crd.go
  pkg/k8s/apis/cilium.io/v1alpha1/register.go
  pkg/k8s/apis/cilium.io/v1alpha1/types.go
  pkg/k8s/apis/cilium.io/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_podinfo.yaml
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/register_v1_crd.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/register.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/zz_generated.deepcopy.go
Labels: release-note/minor
