Repository cilium/tetragon, pull requests merged in 2023-10, with the labels that each got.

#1536 setup-go: Get Go version from go.mod
  .github/workflows/generated-files.yaml
  .github/workflows/gotests.yml
  .github/workflows/podinfo-test.yaml
  .github/workflows/run-e2e-tests.yaml
  .github/workflows/static-checks.yaml
  .github/workflows/vmtests.yml
Labels: release-note/ci

#1534 Use 'go install' to install bom
  .github/workflows/build-clang-image.yaml
  .github/workflows/build-images-ci.yml
  .github/workflows/build-images-releases.yml
Labels: release-note/ci

#1542 Fix build-images-releases.yml
  .github/workflows/build-images-releases.yml
Labels: release-note/ci

#1543 build-images-releases.yml: Fix indentation
  .github/workflows/build-images-releases.yml
Labels: release-note/ci

#1550 event checker: Don't use the word "failure" for pending checks
  api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
  cmd/protoc-gen-go-tetragon/eventchecker/multichecker.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
Labels: release-note/ci

#1544 helm: Make operator imagePullPolicy configurable
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/README.md
  install/kubernetes/templates/operator_deployment.yaml
  install/kubernetes/values.yaml
Labels: release-note/minor, area/helm

#1554 proc_reader: avoid warning for pid=0
  pkg/sensors/exec/procevents/proc_reader.go
Labels: release-note/misc

#1559 bpf: read the task real parent
  bpf/lib/bpf_task.h
Labels: release-note/minor, needs-backport/0.10, needs-backport/0.11

#1557 Renovate: Ignore digest updates for k8s dependencies
  .github/renovate.json5
Labels: area/ci, release-note/ci

#1560 Use Go stdlib instead of golang.org/x/exp
  go.mod
  operator/podinfo/podinfo_controller.go
  pkg/ftrace/ftrace.go
  pkg/metrics/metrics.go
Labels: release-note/misc

#1558 Remove the "operator" init container
  cmd/tetragon/flags.go
  cmd/tetragon/main.go
  install/kubernetes/templates/_container_tetragon.tpl
  install/kubernetes/templates/clusterrole.yaml
  install/kubernetes/templates/daemonset.yaml
  install/kubernetes/templates/tetragon_configmap.yaml
  pkg/option/config.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/expansion_generated.go
  vendor/modules.txt
Labels: release-note/misc

#1574 api: add a policy_name field to kprobe, tracepoint and uprobe events
  api/v1/README.md
  api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
  api/v1/tetragon/tetragon.pb.go
  api/v1/tetragon/tetragon.proto
  contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
  contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
  docs/content/en/docs/reference/grpc-api.md
  pkg/grpc/tracing/tracing.go
  pkg/sensors/tracing/genericuprobe.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
Labels: release-note/minor

#1579 renovate: fix renovate upgrade of Go toolchain
  .github/renovate.json5
  api/go.mod
  contrib/rthooks/tetragon-oci-hook/go.mod
  go.mod
  pkg/k8s/go.mod
Labels: area/ci, release-note/ci

#1584 renovate: fix the way we manually install Go inside the runner
  .github/renovate.json5
Labels: area/ci, release-note/ci

#1488 Reconstruct BTF types more accurately in getKernelType
  pkg/btf/validation.go
Labels: release-note/misc

#1589 refactor: Move flags.go to pkg/option
  cmd/tetragon/conf.go
  cmd/tetragon/conf_test.go
  cmd/tetragon/flags.go
  cmd/tetragon/main.go
  pkg/metrics/metricsconfig/labelfilter.go
  pkg/option/flags.go
Labels: release-note/misc

#1592 pkg/metrics: remove use of x/exp/slices and use stdlib slices
  pkg/metrics/granularmetric.go
  pkg/metrics/metrics.go
Labels: release-note/misc

#1590 bpf: remove cgrpid_tracker
  bpf/lib/bpf_cgroup.h
  bpf/lib/process.h
  bpf/process/bpf_fork.c
  bpf/process/bpf_process_event.h
  bpf/process/policy_filter.h
  pkg/grpc/exec/exec.go
  pkg/sensors/exec/execvemap/execve.go
  pkg/sensors/tracing/kprobe_test.go
  pkg/sensors/tracing/tracepoint_test.go
  pkg/testutils/sensors/load.go
Labels: release-note/bug

#1593 tetragon: Allow to specify rb-* size options with size suffix
  cmd/tetragon/main.go
  pkg/observer/observer.go
  pkg/option/flags.go
  pkg/strutils/strutls.go
  pkg/strutils/strutls_test.go
Labels: release-note/minor

#1594 custom event handling
  pkg/eventhandler/eventhandler.go
  pkg/sensors/tracing/generickprobe.go
  pkg/sensors/tracing/generickprobe_test.go
  pkg/sensors/tracing/generictracepoint.go
  pkg/sensors/tracing/policyhandler.go
  pkg/sensors/tracing/tracepoint_test.go
Labels: release-note/misc

#1587 renovate: enable automerge for pin/pinDigest and patch
  .github/renovate.json5
Labels: area/ci, release-note/ci

#1602 ci: add login-action to docker hub
  .github/workflows/packages-e2e-tests.yaml
Labels: release-note/minor

#1601 ci:tarball-release: remove unnecessary step about installing go
  .github/workflows/build-images-releases.yml
Labels: release-note/minor

#1583 tetragon: Add helper scripts for stats benchmarks
  contrib/bench-stat/graph.sh
  contrib/bench-stat/run.sh
Labels: release-note/minor

#1611 ci: minor refactor to build-images job
  .github/workflows/build-images-ci.yml
Labels: area/ci, release-note/ci

#1612 vendor: fix cilium/tetragon replacement in api
  api/go.mod
  api/vendor/modules.txt
Labels: release-note/misc

#1614 docs: Fix links to policy YAML files
  docs/content/en/docs/concepts/events/json-events.md
  docs/content/en/docs/getting-started/enforcement.md
  docs/content/en/docs/getting-started/file-events.md
  docs/content/en/docs/getting-started/network.md
  docs/content/en/docs/installation/package.md
Labels: release-note/docs

#1617 tetragon: docs, minor updates to metrics concepts
  docs/content/en/docs/concepts/metrics.md
Labels: release-note/docs

#1621 docs: tracing policy concept updates
  docs/content/en/docs/concepts/tracing-policy/_index.md
  docs/content/en/docs/concepts/tracing-policy/example.md
  docs/content/en/docs/concepts/tracing-policy/hooks.md
Labels: release-note/docs

#1616 tetragon: docs, trnasform events into single page
  docs/content/en/docs/concepts/events.md
  docs/content/en/docs/concepts/events/_index.md
  docs/content/en/docs/concepts/events/grpc-events.md
  docs/content/en/docs/concepts/events/json-events.md
Labels: release-note/docs

#1644 helm: Fix selector labels for the operator deployment
  install/kubernetes/templates/operator_deployment.yaml
Labels: release-blocker, release-note/bug

#1639 tetra policyfilter command
  cmd/tetra/commands_linux.go
  cmd/tetra/dump/dump.go
  cmd/tetra/policyfilter/policyfilter.go
  pkg/policyfilter/map.go
Labels: release-note/misc

#1649 ci: fix CI for external contributors
  .github/workflows/packages-e2e-tests.yaml
Labels: area/ci, release-note/ci

#1638 helm: add service monitor scrape interval config
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/README.md
  install/kubernetes/templates/servicemonitor.yaml
  install/kubernetes/values.yaml
Labels: release-note/minor, area/helm

#1647 helm: enable policyfilter by default
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/README.md
  install/kubernetes/values.yaml
Labels: release-note/minor

#1655 Prepare for v1.0.0-rc2 release
  docs/content/en/docs/reference/helm-chart.md
  docs/hugo.toml
  install/kubernetes/Chart.yaml
  install/kubernetes/README.md
  install/kubernetes/values.yaml
Labels: release-note/misc

#1631 tetragon: for now drop benchmark section
  docs/content/en/docs/benchmarks/_index.md
  docs/content/en/docs/getting-started/enforcement.md
Labels: release-note/docs

#1659 Prepare for v1.0.0-rc.2 release
  docs/content/en/docs/reference/helm-chart.md
  docs/hugo.toml
  install/kubernetes/Chart.yaml
  install/kubernetes/README.md
  install/kubernetes/values.yaml
Labels: release-note/misc

#1657 doc: replace dead links in README.md
  README.md
Labels: release-note/docs

#1661 Prepare for v1.0.0-rc.3 release
  docs/content/en/docs/reference/helm-chart.md
  docs/hugo.toml
  install/kubernetes/Chart.yaml
  install/kubernetes/README.md
  install/kubernetes/values.yaml
Labels: release-note/misc

#1663 docs: Typo TOCTU -> TOCTOU
  docs/content/en/docs/concepts/tracing-policy/_index.md
Labels: area/documentation, release-note/docs

#1630 docs: update enforcement page
  docs/content/en/docs/concepts/enforcement/_index.md
  docs/content/en/docs/concepts/tracing-policy/selectors.md
Labels: release-note/docs

#1671 vmtests: bump timeout and start multiple job for builds
  .github/workflows/vmtests.yml
Labels: area/ci, release-note/ci

#1677 Update the Star Wars demo app URL
  docs/content/en/docs/getting-started/install-k8s.md
  docs/content/en/docs/use-cases/linux-process-credentials/monitor-changes-at-kernel.md
  docs/content/en/docs/use-cases/linux-process-credentials/syscalls-monitoring.md
  docs/content/en/docs/use-cases/process-lifecycle/advanced-process-execution.md
  docs/content/en/docs/use-cases/security-profiles/record-linux-capabilities.md
  docs/hugo.toml
  docs/layouts/shortcodes/demo-app-url.html
Labels: release-note/docs

#1681 Prepare for v1.0.0-rc.4 release
  docs/content/en/docs/reference/helm-chart.md
  docs/hugo.toml
  install/kubernetes/Chart.yaml
  install/kubernetes/README.md
  install/kubernetes/values.yaml
Labels: release-note/misc

#1689 gh: use cosign sign -y
  .github/workflows/build-clang-image.yaml
  .github/workflows/build-images-ci.yml
  .github/workflows/build-images-releases.yml
Labels: release-note/ci

#1624 tetragon: docs, minor updates to metrics concepts
  docs/content/en/docs/concepts/metrics.md
Labels: area/documentation, release-note/docs

#1673 Minor docs changes for 1.0 messaging
  docs/content/en/docs/overview/_index.md
  docs/layouts/partials/footer.html
Labels: release-note/docs

#1691 Prepare for v1.0.0-rc.5 release
  docs/content/en/docs/reference/helm-chart.md
  docs/hugo.toml
  install/kubernetes/Chart.yaml
  install/kubernetes/README.md
  install/kubernetes/values.yaml
Labels: release-note/misc

#1686 doc: Add intructions on how to create EKS and AKS clusters
  docs/content/en/docs/getting-started/install-k8s.md
Labels: area/documentation, release-note/docs

#1693 Use a message copy to apply fieldFilters in exec events
  cmd/tetra/getevents/io_reader_client.go
  pkg/server/server.go
Labels: release-note/bug
