Repository cilium/tetragon, pull requests merged in 2023-05, with the labels that each got.

#956 dependabot: fix a tag issue with alpine-curl image
  .github/dependabot.yml
Labels: dependabot-fail

#965 Add documentation in the CRD for `maxData` and `returnCopy` flags and update doc
  docs/content/en/docs/reference/tracing-policy.md
  pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
  pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
  pkg/k8s/apis/cilium.io/v1alpha1/types.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
Labels: area/documentation

#972 github: add feature request issue template
  .github/ISSUE_TEMPLATE/feature_request_template.yaml
Labels: kind/enhancement

#981 docs: add FAQ entry about CGO related issues in pkg/bpf
  docs/content/en/docs/faq/_index.md
Labels: area/documentation

#993 docs: add last two Tetragon KubeCon EU 2023 prez
  docs/content/en/docs/resources/_index.md
Labels: area/documentation

#944 fix[helm]: remove useless 'if' around a 'with'
  install/kubernetes/templates/daemonset.yaml
Labels: kind/cleanup

#991 docs: add a "install tetra CLI" guide to getting started
  docs/content/en/docs/getting-started/configuration.md
  docs/content/en/docs/getting-started/install-tetra-cli.md
Labels: area/documentation

#1009 docs: add a script to export the generated API doc to references
  api/Makefile
  api/export-docs.sh
  docs/content/en/docs/reference/grpc-api.md
Labels: area/documentation

#1006 docs: add an FAQ entry about BTF requirement
  docs/content/en/docs/faq/_index.md
Labels: area/documentation

#959 api: add comments on fields for reference docs
  api/v1/README.md
  api/v1/tetragon/events.pb.go
  api/v1/tetragon/events.proto
  api/v1/tetragon/tetragon.pb.go
  api/v1/tetragon/tetragon.proto
  docs/content/en/docs/reference/grpc-api.md
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
Labels: area/documentation

#999 cleanup: remove mistakenly committed coverage artifacts
  pkg/policyfilter/coverage.html
  pkg/policyfilter/coverage.out
Labels: kind/cleanup

#1026 docs: fix sticky header, TOC scrolling and add search bar
  docs/assets/scss/sidebar.scss
  docs/assets/scss/theme/main-container.scss
  docs/assets/scss/theme/navbar.scss
  docs/assets/scss/theme/sidebar-toc.scss
  docs/assets/scss/theme/sidebar-tree.scss
  docs/layouts/partials/sidebar-tree.html
Labels: area/documentation
