Repository cilium/tetragon, pull requests merged in 2023-11, with the labels that each got.

#1692 ci: check docs links fixes and configuration
  .github/lychee.toml
  .github/workflows/check-links-cron.yaml
  .github/workflows/check-links-pr.yaml
Labels: area/ci, release-note/ci

#1613 ci: fix branch name
  .github/workflows/build-images-ci.yml
Labels: release-note/misc

#1698 Prepare for v1.0.0 release
  docs/content/en/docs/reference/helm-chart.md
  docs/hugo.toml
  install/kubernetes/Chart.yaml
  install/kubernetes/README.md
  install/kubernetes/values.yaml
Labels: release-note/misc

#1699 starting 1.1 development
  pkg/k8s/apis/cilium.io/v1alpha1/version.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go
Labels: release-note/misc

#1709 docs: update tetragon.io title
  docs/content/en/_index.html
  docs/hugo.toml
Labels: area/documentation, release-note/docs

#1702 backports/v1.0: Add a metric to provide per-event missed events
  bpf/alignchecker/bpf_alignchecker.c
  bpf/cgroup/bpf_cgroup_events.h
  bpf/lib/msg_types.h
  bpf/lib/process.h
  bpf/process/bpf_execve_event.c
  bpf/process/bpf_exit.h
  bpf/process/bpf_fork.c
  bpf/process/bpf_generic_kprobe.c
  bpf/process/bpf_generic_retkprobe.c
  bpf/process/bpf_generic_tracepoint.c
  bpf/process/bpf_generic_uprobe.c
  bpf/process/bpf_loader.c
  bpf/process/data_event.h
  bpf/process/types/basic.h
  pkg/alignchecker/alignchecker.go
  pkg/api/processapi/processapi.go
  pkg/metrics/eventmetrics/collector.go
  pkg/metrics/eventmetrics/eventmetrics.go
  pkg/metrics/metricsconfig/initmetrics.go
  pkg/sensors/base/base.go
Labels: area/metrics, release-note/minor

#1713 renovate: let renovate update gops in Dockerfile
  .github/renovate.json5
  Dockerfile
Labels: area/ci, release-note/ci

#1712 filters/fields: do a deep copy before filtering
  cmd/tetra/getevents/io_reader_client.go
  pkg/filters/fields.go
  pkg/filters/fields_test.go
  pkg/server/server.go
Labels: kind/bug, release-note/bug

#1726 filters/fields: do a deep copy before filtering
  cmd/tetra/getevents/io_reader_client.go
  pkg/filters/fields.go
  pkg/filters/fields_test.go
  pkg/server/server.go
Labels: release-note/bug

#1727 filters/fields: do a deep copy before filtering
  cmd/tetra/getevents/io_reader_client.go
  pkg/filters/fields.go
  pkg/filters/fields_test.go
  pkg/server/server.go
Labels: release-note/bug

#1678 pkg/option: add metrics-label-filter flags
  docs/content/en/docs/reference/daemon-flags.md
  examples/configuration/tetragon.yaml
  pkg/option/flags.go
Labels: area/metrics, release-note/bug

#1734 docs: remove mention of obsolete map_linux.go
  docs/content/en/docs/faq/_index.md
Labels: release-note/docs

#1735 pkg/bench: disable BPF stats collection at the end of execution
  pkg/bench/bpfstats.go
  pkg/bench/trace.go
Labels: release-note/misc

#1742 renovate: enable stable support for v1.0 and fixes
  .github/renovate.json5
  .github/workflows/renovate.yaml
Labels: area/ci, release-note/ci

#1752 renovate: try to fix Go updates for stable branches
  .github/renovate.json5
Labels: area/ci, release-note/ci

#1756 renovate: fix allowed version for Go upgrades in 1.0 branch
  .github/renovate.json5
Labels: area/ci, release-note/ci

#1758 renovate: add digest in Golang Docker image in Makefile.cli
  .github/renovate.json5
  Makefile.cli
Labels: area/ci, release-note/ci

#1119 Issue 1108/replace the use of viper.bind flags with variables binding
  cmd/tetra/common/client.go
  cmd/tetra/common/flags.go
  cmd/tetra/getevents/getevents.go
  cmd/tetra/main.go
Labels: area/userspace, release-note/misc

#1730 Makefile: also use JOBS for test-compile
  Makefile
Labels: release-note/misc

#1760 chore: site description update
  docs/hugo.toml
Labels: release-note/docs

#1740 e2e: wait for tracing policy fixes
  tests/e2e/helpers/grpc/grpc.go
Labels: release-note/ci

#1770 tetragon: fix hang on error in tetragonExecute
  cmd/tetragon/main.go
Labels: release-blocker, release-note/bug

#1777 podinfo: Handle an expected error gracefully
  operator/podinfo/podinfo_controller.go
Labels: release-note/misc

#1780 doc: Clarified Docker Desktop on MacOS FAQ
  docs/content/en/docs/faq/_index.md
Labels: release-note/docs

#1779 String: Increase prefix size from 128 to 256 chars
  bpf/process/string_maps.h
  pkg/selectors/selectors.go
  pkg/sensors/tracing/selectors.go
Labels: release-note/minor

#1753 Update install-k8s.md
  docs/content/en/docs/getting-started/install-k8s.md
Labels: area/documentation, release-note/docs

#1807 Arg validation: Add mappings for sock and skb
  pkg/btf/validation.go
Labels: release-note/bug

#1811 fork-tester: remove connect to 8.8.8.8
  contrib/tester-progs/fork-tester.c
  pkg/sensors/exec/fork_test.go
Labels: release-note/ci

#1785 e2e: Fix logger in e2e tests
  go.mod
  go.sum
  tests/e2e/runners/runners.go
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/SECURITY.md
  vendor/github.com/go-logr/logr/funcr/funcr.go
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/go-logr/logr/slogr/sloghandler.go
  vendor/github.com/go-logr/logr/slogr/slogr.go
  vendor/github.com/go-logr/logr/slogr/slogsink.go
  vendor/k8s.io/klog/v2/.golangci.yaml
  vendor/k8s.io/klog/v2/internal/buffer/buffer.go
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues_no_slog.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues_slog.go
  vendor/k8s.io/klog/v2/internal/sloghandler/sloghandler_slog.go
  vendor/k8s.io/klog/v2/internal/verbosity/verbosity.go
  vendor/k8s.io/klog/v2/k8s_references_slog.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/k8s.io/klog/v2/klogr_slog.go
  vendor/k8s.io/klog/v2/textlogger/options.go
  vendor/k8s.io/klog/v2/textlogger/textlogger.go
  vendor/k8s.io/klog/v2/textlogger/textlogger_slog.go
  vendor/modules.txt
Labels: release-note/ci

#1818 helm: Don't mount /var/lib/tetragon/metadata
  install/kubernetes/templates/_container_tetragon.tpl
  install/kubernetes/templates/daemonset.yaml
Labels: kind/cleanup, release-note/misc, area/helm
