Repository cilium/tetragon, pull requests merged in 2023-12, with the labels that each got.

#1797 helm: adding optional to expose tetragon-operator metrics
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/README.md
  install/kubernetes/templates/operator_deployment.yaml
  install/kubernetes/templates/operator_service.yaml
  install/kubernetes/test.sh
  install/kubernetes/values.yaml
  operator/cmd/serve/serve.go
Labels: release-note/minor, area/helm

#1838 tracingpolicy: add a stack traces example
  examples/tracingpolicy/stack_traces.yaml
Labels: release-note/misc

#1841 backports/v1.0: helm: Fix templating securityContext and tolerations
  install/kubernetes/templates/daemonset.yaml
Labels: kind/bug, kind/backport, release-note/bug, area/helm

#1832 linters: add makezero and fix a related bug
  .golangci.yml
  pkg/btf/validation.go
  pkg/reader/network/network.go
  pkg/syscallinfo/syscallinfo.go
Labels: area/ci, release-note/misc

#1852 workflows: add independent go-version for setup-go actions
  .github/renovate.json5
  .github/workflows/build-clang-image.yaml
  .github/workflows/build-images-ci.yml
  .github/workflows/build-images-releases.yml
  .github/workflows/generated-files.yaml
  .github/workflows/gotests.yml
  .github/workflows/lint-codeql.yml
  .github/workflows/podinfo-test.yaml
  .github/workflows/run-e2e-tests.yaml
  .github/workflows/static-checks.yaml
  .github/workflows/vmtests.yml
Labels: release-note/ci

#1848 Remove pod.labels field
  api/v1/README.md
  api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
  api/v1/tetragon/tetragon.pb.go
  api/v1/tetragon/tetragon.proto
  contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
  contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
  docs/content/en/docs/reference/grpc-api.md
  examples/eventchecker/process_exec.yaml
  pkg/fieldfilters/fields_test.go
  pkg/process/podinfo.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
Labels: release-note/breaking-changes

#1865 workflow: fix PR link checker to check local branch links
  .github/workflows/check-links-pr.yaml
Labels: area/documentation, area/ci, release-note/ci

#1871 testutils: Fix RepoRootPath when Tetragon is vendored
  pkg/testutils/path.go
Labels: release-note/misc

#1882 fieldfilters: fix regression with missing top-level info and add test
  pkg/fieldfilters/fields.go
  pkg/fieldfilters/fields_test.go
Labels: release-note/bug, needs-backport/1.0

#1883 backports/v1.0: fieldfilters: fix regression with missing top-level info and add test
  pkg/fieldfilters/fields.go
  pkg/fieldfilters/fields_test.go
Labels: release-note/bug

#1885 Prepare for v1.0.1 release
  docs/content/en/docs/reference/helm-chart.md
  docs/hugo.toml
  install/kubernetes/Chart.yaml
  install/kubernetes/README.md
  install/kubernetes/values.yaml
Labels: release-note/misc

#1873 docs: add privacy-aware GoatCounter analytics
  docs/layouts/partials/hooks/head-end.html
Labels: area/documentation, release-note/docs

#1846 helm: Add extensions templates
  install/kubernetes/tetragon/templates/_container_tetragon.tpl
  install/kubernetes/tetragon/templates/_extensions.tpl
  install/kubernetes/tetragon/templates/daemonset.yaml
  install/kubernetes/tetragon/templates/tetragon_configmap.yaml
Labels: release-note/misc, area/helm

#1890 ci: fix tetragon go test ci job
  .github/workflows/gotests.yml
  contrib/tester-progs/Makefile
Labels: release-note/minor
