Repository cilium/tetragon, pull requests merged in 2023-07, with the labels that each got.

#1212 renovate: ungroup Go minor updates
  .github/renovate.json5
Labels: area/ci

#1213 renovate: migrate config for v36 release
  .github/renovate.json5
Labels: area/ci

#1197 issue templates: improve bug report template
  .github/ISSUE_TEMPLATE/bug_report_template.yaml
Labels: kind/enhancement

#1228 Pass Namespace in metrics options instead of prefixing metric names
  pkg/grpc/tracing/stats.go
  pkg/metrics/consts/consts.go
  pkg/metrics/errormetrics/errormetrics.go
  pkg/metrics/eventcachemetrics/eventcachemetrics.go
  pkg/metrics/eventmetrics/eventmetrics.go
  pkg/metrics/kprobemetrics/kprobemetrics.go
  pkg/metrics/mapmetrics/mapmetrics.go
  pkg/metrics/opcodemetrics/opcodemetrics.go
  pkg/metrics/policyfilter/policyfilter.go
  pkg/metrics/processexecmetrics/processexecmetrics.go
  pkg/metrics/ringbufmetrics/ringbufmetrics.go
  pkg/metrics/syscallmetrics/syscallmetrics.go
  pkg/metrics/watchermetrics/watchermetrics.go
Labels: area/metrics

#1223 pkg/filters: make field filters work with snake case fields
  pkg/filters/fields.go
  pkg/filters/fields_test.go
Labels: release-note/minor
