Repository cilium/tetragon, pull requests merged in 2023-09, with the labels that each got.

#1405 tetragon: Add missing selectors newBinVals setup
  pkg/selectors/selectors.go
Labels: release-note/minor

#1414 Prepare for v0.11.0 release
  docs/content/en/docs/reference/helm-chart.md
  docs/hugo.toml
  install/kubernetes/Chart.yaml
  install/kubernetes/README.md
  install/kubernetes/values.yaml
Labels: release-note/misc

#1413 Starting 0.12 development
  pkg/k8s/apis/cilium.io/v1alpha1/register.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/register.go
Labels: release-note/misc

#1415 Fixes in the release template
  .github/ISSUE_TEMPLATE/release_template.md
Labels: release-note/misc

#1416 pkg/metrics: add common go&gRPC prometheus metrics
  api/go.mod
  api/go.sum
  api/vendor/golang.org/x/net/http2/transport.go
  api/vendor/golang.org/x/text/unicode/norm/trie.go
  api/vendor/modules.txt
  go.mod
  go.sum
  pkg/metrics/config/initmetrics.go
  pkg/version/metrics.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/LICENSE
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/client_metrics.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/client_options.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/constants.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/options.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/reporter.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/server_metrics.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus/server_options.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/COPYRIGHT
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/LICENSE
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/callmeta.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/client.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/reporter.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/server.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/github.com/prometheus/common/expfmt/text_parse.go
  vendor/github.com/prometheus/procfs/Makefile.common
  vendor/github.com/prometheus/procfs/fs.go
  vendor/github.com/prometheus/procfs/fs_statfs_notype.go
  vendor/github.com/prometheus/procfs/fs_statfs_type.go
  vendor/github.com/prometheus/procfs/proc.go
  vendor/github.com/prometheus/procfs/proc_psi.go
  vendor/github.com/prometheus/procfs/proc_smaps.go
  vendor/github.com/prometheus/procfs/stat.go
  vendor/github.com/prometheus/procfs/thread.go
  vendor/github.com/stoewer/go-strcase/README.md
  vendor/github.com/stoewer/go-strcase/camel.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/oauth2/internal/oauth2.go
  vendor/golang.org/x/oauth2/internal/token.go
  vendor/golang.org/x/oauth2/token.go
  vendor/golang.org/x/text/unicode/norm/trie.go
  vendor/modules.txt
Labels: release-note/minor

#1401 tetragon: Adding lists documentation
  docs/content/en/docs/concepts/tracing-policy/hooks.md
Labels: release-note/minor

#1404 docs: fix footer
  docs/assets/scss/footer.scss
  docs/layouts/partials/footer.html
Labels: release-note/misc

#1426 Remove cilium-bpf configuration parameter
  cmd/tetragon/flags.go
  cmd/tetragon/main.go
  examples/configuration/tetragon.yaml
  install/kubernetes/templates/tetragon_configmap.yaml
  pkg/bench/bench.go
  pkg/observer/observer.go
  pkg/observer/observertesthelper/observer_test_helper.go
  pkg/option/config.go
  pkg/sensors/collection.go
  pkg/sensors/exec/exec_test.go
  pkg/sensors/handler.go
  pkg/sensors/load.go
  pkg/sensors/manager.go
  pkg/sensors/manager_test.go
  pkg/sensors/program/cgroup/cgroup.go
  pkg/sensors/sensors.go
  pkg/sensors/tracing/kprobe_test.go
  pkg/testutils/sensors/sensors.go
Labels: release-note/misc

#1437 observer_test_helper: make helpers generic over TB
  pkg/observer/observertesthelper/observer_test_helper.go
  pkg/testutils/filenames.go
  pkg/testutils/logcapture.go
Labels: release-note/misc

#1435 renovate: add release-note/dependency label to PRs
  .github/renovate.json5
Labels: area/ci, release-note/ci

#1432 Use a message copy to apply fieldFilters in exec events
  cmd/tetra/getevents/io_reader_client.go
  pkg/server/server.go
Labels: release-note/bug

#1440 Modify Operator cluster role
  install/kubernetes/templates/operator_clusterrolebinding.yaml
Labels: release-note/misc

#1443 docs: document kernel version and requirement
  docs/content/en/docs/faq/_index.md
  docs/content/en/docs/getting-started/try-tetragon-linux.md
Labels: release-note/docs

#1449 CODEOWNERS: multiple fixes and move file in `.github`
  .github/CODEOWNERS
Labels: release-note/ci

#1380 README: simplify the README to refer to the documentation
  README.md
Labels: area/documentation

#1407 helm: update livenessProbe to retry 5 times before failing
  install/kubernetes/templates/_container_tetragon.tpl
Labels: release-note/minor

#1453 tetragon: Add metric to report rate limited events
  pkg/metrics/config/initmetrics.go
  pkg/metrics/ratelimitmetrics/ratelimitmetrics.go
  pkg/ratelimit/ratelimit.go
Labels: release-note/minor

#1456 Update module github.com/pelletier/go-toml/v2 to v2.1.0
  go.mod
  go.sum
  vendor/github.com/pelletier/go-toml/v2/.goreleaser.yaml
  vendor/github.com/pelletier/go-toml/v2/LICENSE
  vendor/github.com/pelletier/go-toml/v2/README.md
  vendor/github.com/pelletier/go-toml/v2/ci.sh
  vendor/github.com/pelletier/go-toml/v2/decode.go
  vendor/github.com/pelletier/go-toml/v2/marshaler.go
  vendor/github.com/pelletier/go-toml/v2/unmarshaler.go
  vendor/github.com/pelletier/go-toml/v2/unstable/parser.go
  vendor/modules.txt
Labels: release-note/misc

#1454 bpf: fix verification error in bpf_execve_event
  bpf/process/data_event.h
Labels: release-note/bug, needs-backport/0.11

#1463 docs: fix link in README and remove unreliable link to busybox
  README.md
  docs/content/en/docs/use-cases/process-lifecycle/advanced-process-execution.md
Labels: area/documentation, release-note/docs

#1459 Refactor files under operator directory
  operator/cmd/root.go
  operator/main.go
  operator/option/config.go
  pkg/cmdref/cmdref.go
Labels: release-note/misc

#1468 Move CustomResourceDefinitionSchemaVersion to a separate file
  pkg/k8s/apis/cilium.io/v1alpha1/register.go
  pkg/k8s/apis/cilium.io/v1alpha1/version.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/register.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go
Labels: release-note/misc

#1462 Revert "Update module github.com/pelletier/go-toml/v2 to v2.1.0"
  go.mod
  go.sum
  vendor/github.com/pelletier/go-toml/v2/.goreleaser.yaml
  vendor/github.com/pelletier/go-toml/v2/LICENSE
  vendor/github.com/pelletier/go-toml/v2/README.md
  vendor/github.com/pelletier/go-toml/v2/ci.sh
  vendor/github.com/pelletier/go-toml/v2/decode.go
  vendor/github.com/pelletier/go-toml/v2/marshaler.go
  vendor/github.com/pelletier/go-toml/v2/unmarshaler.go
  vendor/github.com/pelletier/go-toml/v2/unstable/parser.go
  vendor/modules.txt
Labels: release-note/misc

#1400 helm: Allow multiple installations of the Tetragon Helm chart
  install/kubernetes/templates/clusterrole.yaml
  install/kubernetes/templates/clusterrolebinding.yml
  install/kubernetes/templates/daemonset.yaml
  install/kubernetes/templates/operator_clusterrole.yaml
  install/kubernetes/templates/operator_clusterrolebinding.yaml
  install/kubernetes/templates/operator_configmap.yaml
  install/kubernetes/templates/operator_deployment.yaml
  install/kubernetes/templates/operator_serviceaccount.yaml
  install/kubernetes/templates/service.yaml
  install/kubernetes/templates/serviceaccount.yaml
  install/kubernetes/templates/tetragon_configmap.yaml
Labels: release-note/minor

#1474 renovate: rename correctly the lvh image name in config
  .github/renovate.json5
Labels: area/ci, release-note/ci

#1476 renovate: add both lvh-images/kind and kernel-images
  .github/renovate.json5
Labels: area/ci, release-note/ci

#1479 k8s: Generate PodInfo client
  pkg/k8s/apis/cilium.io/v1alpha1/types.go
  pkg/k8s/client/clientset/versioned/typed/cilium.io/v1alpha1/cilium.io_client.go
  pkg/k8s/client/clientset/versioned/typed/cilium.io/v1alpha1/fake/fake_cilium.io_client.go
  pkg/k8s/client/clientset/versioned/typed/cilium.io/v1alpha1/fake/fake_podinfo.go
  pkg/k8s/client/clientset/versioned/typed/cilium.io/v1alpha1/generated_expansion.go
  pkg/k8s/client/clientset/versioned/typed/cilium.io/v1alpha1/podinfo.go
  pkg/k8s/client/informers/externalversions/cilium.io/v1alpha1/interface.go
  pkg/k8s/client/informers/externalversions/cilium.io/v1alpha1/podinfo.go
  pkg/k8s/client/informers/externalversions/generic.go
  pkg/k8s/client/listers/cilium.io/v1alpha1/expansion_generated.go
  pkg/k8s/client/listers/cilium.io/v1alpha1/podinfo.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
  vendor/github.com/cilium/tetragon/pkg/k8s/client/clientset/versioned/typed/cilium.io/v1alpha1/cilium.io_client.go
  vendor/github.com/cilium/tetragon/pkg/k8s/client/clientset/versioned/typed/cilium.io/v1alpha1/generated_expansion.go
  vendor/github.com/cilium/tetragon/pkg/k8s/client/clientset/versioned/typed/cilium.io/v1alpha1/podinfo.go
  vendor/github.com/cilium/tetragon/pkg/k8s/client/informers/externalversions/cilium.io/v1alpha1/interface.go
  vendor/github.com/cilium/tetragon/pkg/k8s/client/informers/externalversions/cilium.io/v1alpha1/podinfo.go
  vendor/github.com/cilium/tetragon/pkg/k8s/client/informers/externalversions/generic.go
  vendor/github.com/cilium/tetragon/pkg/k8s/client/listers/cilium.io/v1alpha1/expansion_generated.go
  vendor/github.com/cilium/tetragon/pkg/k8s/client/listers/cilium.io/v1alpha1/podinfo.go
Labels: release-note/misc

#1480 docs(tracing-policy) - Grammar and punctuation
  docs/content/en/docs/concepts/tracing-policy/example.md
Labels: release-note/docs

#1491 watcher: Implement FindPodInfoByIP
  pkg/observer/observertesthelper/observer_test_helper.go
  pkg/watcher/fake.go
  pkg/watcher/watcher.go
  pkg/watcher/watcher_test.go
  vendor/github.com/cilium/tetragon/pkg/k8s/client/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/cilium/tetragon/pkg/k8s/client/clientset/versioned/fake/doc.go
  vendor/github.com/cilium/tetragon/pkg/k8s/client/clientset/versioned/fake/register.go
  vendor/github.com/cilium/tetragon/pkg/k8s/client/clientset/versioned/typed/cilium.io/v1alpha1/fake/doc.go
  vendor/github.com/cilium/tetragon/pkg/k8s/client/clientset/versioned/typed/cilium.io/v1alpha1/fake/fake_cilium.io_client.go
  vendor/github.com/cilium/tetragon/pkg/k8s/client/clientset/versioned/typed/cilium.io/v1alpha1/fake/fake_podinfo.go
  vendor/github.com/cilium/tetragon/pkg/k8s/client/clientset/versioned/typed/cilium.io/v1alpha1/fake/fake_tracingpolicy.go
  vendor/github.com/cilium/tetragon/pkg/k8s/client/clientset/versioned/typed/cilium.io/v1alpha1/fake/fake_tracingpolicynamespaced.go
  vendor/modules.txt
Labels: release-note/misc

#1458 Add IPv6 support to BPF rate limit
  bpf/process/types/basic.h
Labels: release-note/minor

#1492 operator: Call crd.RegisterCRDs() from operator deployment
  install/kubernetes/templates/operator_clusterrole.yaml
  install/kubernetes/templates/operator_deployment.yaml
  operator/cmd/common/common.go
  operator/cmd/root.go
  operator/cmd/serve/serve.go
Labels: release-note/misc

#1493 podinfo: Populate workload info
  operator/podinfo/podinfo_controller.go
  operator/podinfo/podinfo_controller_test.go
  pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_podinfo.yaml
  pkg/k8s/apis/cilium.io/v1alpha1/types.go
  pkg/k8s/apis/cilium.io/v1alpha1/version.go
  pkg/k8s/apis/cilium.io/v1alpha1/zz_generated.deepcopy.go
  pkg/process/workload.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_podinfo.yaml
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/zz_generated.deepcopy.go
Labels: release-note/misc

#1499 api: Add workload_kind field to Pod message
  api/v1/README.md
  api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
  api/v1/tetragon/tetragon.pb.go
  api/v1/tetragon/tetragon.proto
  docs/content/en/docs/reference/grpc-api.md
  pkg/process/podinfo.go
  pkg/process/podinfo_test.go
  pkg/process/workload.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
Labels: release-note/misc

#1256 tetragon: improve how we handle TIDs and GetProcessCopy()
  bpf/process/bpf_execve_event.c
  bpf/process/bpf_exit.h
  bpf/process/bpf_fork.c
  bpf/process/generic_calls.h
  pkg/eventcache/eventcache.go
  pkg/grpc/exec/exec.go
  pkg/grpc/tracing/tracing.go
  pkg/process/process.go
Labels: release-note/minor

#1494 bpf: add DEBUG() macro
  Makefile
  bpf/Makefile
  bpf/lib/common.h
Labels: release-note/misc

#1498 cmd: Remove deprecated --config-file flag
  cmd/tetragon/flags.go
  cmd/tetragon/main.go
Labels: area/userspace, release-note/minor

#1500 helm: Don't create operator ClusterRoleBinding if podWatcher is disabled
  install/kubernetes/templates/operator_clusterrolebinding.yaml
Labels: kind/bug, release-note/misc, area/helm

#1501 operator: Clean up Helm values
  .github/workflows/podinfo-test.yaml
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/README.md
  install/kubernetes/templates/_container_tetragon.tpl
  install/kubernetes/templates/daemonset.yaml
  install/kubernetes/templates/operator_clusterrole.yaml
  install/kubernetes/templates/operator_clusterrolebinding.yaml
  install/kubernetes/templates/operator_configmap.yaml
  install/kubernetes/templates/operator_deployment.yaml
  install/kubernetes/templates/operator_serviceaccount.yaml
  install/kubernetes/values.yaml
  operator/cmd/serve/serve.go
Labels: release-note/misc

#1502 metrics: report metric errors when caching pids
  pkg/grpc/exec/exec.go
  pkg/metrics/errormetrics/errormetrics.go
  pkg/process/process.go
Labels: release-note/minor

#1516 docs: fixes anchor links
  docs/assets/scss/theme/content.scss
Labels: release-note/docs

#1515 tracing: check for empty returnArg
  pkg/sensors/tracing/generickprobe.go
Labels: release-note/minor

#1444 metrics: Add metrics label filter configuration
  cmd/tetragon/flags.go
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/README.md
  install/kubernetes/templates/tetragon_configmap.yaml
  install/kubernetes/values.yaml
  pkg/metrics/config/initmetrics.go
  pkg/metrics/consts/consts.go
  pkg/metrics/eventmetrics/eventmetrics.go
  pkg/metrics/eventmetrics/eventmetrics_test.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/metrics/syscallmetrics/syscallmetrics.go
  pkg/option/config.go
Labels: area/metrics, release-note/minor

#1530 Dockerfile.clang: Don't pin clang patch version
  Dockerfile.clang
Labels: release-note/ci

#1532 packages-e2e-tests: Don't fail fast
  .github/workflows/packages-e2e-tests.yaml
Labels: release-note/ci
