Repository cilium/tetragon, pull requests merged in 2024-04, with the labels that each got.

#2174 ci/static-checks: ensure no binary files are checked in
  .github/workflows/static-checks.yaml
Labels: release-note/ci

#2276 cves: add detection of XZ backdoor in OpenSSH
  examples/policylibrary/cves/cve-2024-3094-xz-ssh.yaml
Labels: release-note/minor

#2258 Makefile: add native build support for arm64 MacOS
  Makefile
Labels: release-note/misc

#2281 tracingpolicy: comment message field for older versions support
  examples/policylibrary/cves/cve-2024-3094-xz-ssh.yaml
Labels: release-note/minor

#2267 backports/willfindlay/1.0/redaction filters
  api/v1/README.md
  api/v1/tetragon/events.pb.go
  api/v1/tetragon/events.pb.json.go
  api/v1/tetragon/events.proto
  cmd/tetragon/main.go
  contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.json.go
  contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
  docs/content/en/docs/concepts/events.md
  docs/content/en/docs/reference/daemon-flags.md
  docs/content/en/docs/reference/grpc-api.md
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/README.md
  install/kubernetes/templates/tetragon_configmap.yaml
  install/kubernetes/values.yaml
  pkg/bench/bench.go
  pkg/exporter/exporter_test.go
  pkg/fieldfilters/redaction.go
  pkg/fieldfilters/redaction_test.go
  pkg/grpc/exec/exec_test_helper.go
  pkg/grpc/process_manager.go
  pkg/grpc/process_manager_test.go
  pkg/observer/observertesthelper/observer_test_helper.go
  pkg/option/flags.go
  pkg/server/server.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.json.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
  vendor/google.golang.org/protobuf/internal/msgfmt/format.go
  vendor/google.golang.org/protobuf/reflect/protopath/path.go
  vendor/google.golang.org/protobuf/reflect/protopath/step.go
  vendor/google.golang.org/protobuf/reflect/protorange/range.go
  vendor/modules.txt
Labels: kind/backport, release-note/major

#2283 Makefile: fix a missing 'vendor' target in oci-hook
  Makefile
Labels: kind/bug, release-note/ci

#2288 tetragon: cleanup pfilter.h to make it readable
  bpf/process/pfilter.h
Labels: release-note/misc

#2289 jsonchecker: reset state of the export file
  pkg/jsonchecker/jsonchecker.go
  pkg/testutils/filenames.go
Labels: release-note/misc

#2287 metrics: Remove pod from the queue after deleting metrics
  pkg/metrics/metricwithpod.go
Labels: area/metrics, release-note/bug

#2310 docs: fix contribution-guide docker run
  docs/content/en/docs/contribution-guide/development-setup.md
Labels: area/documentation, release-note/docs

#2312 BTF validation fixes
  pkg/btf/validation.go
Labels: release-note/misc

#2311 docs: update demo app url
  docs/hugo.toml
Labels: area/documentation, release-note/docs

#2314 backports/1.0: exporter: fix hang when exporter fails to start
  pkg/server/server.go
Labels: kind/bug, release-note/bug

#2254 Prepare for v1.0.3 release
  docs/content/en/docs/reference/helm-chart.md
  docs/hugo.toml
  install/kubernetes/Chart.yaml
  install/kubernetes/README.md
  install/kubernetes/values.yaml
Labels: release-note/misc

#2316 Update bug out tar file
  docs/content/en/docs/troubleshooting/_index.md
Labels: area/documentation, release-note/docs

#2319 validate-crd: use SHAs for diff
  .github/workflows/validate-crd.yaml
Labels: release-note/ci

#2318 Update events.md
  docs/content/en/docs/concepts/events.md
Labels: area/documentation, release-note/docs

#2322 filters/redaction: fix crash related to redaction filters and improve performance
  api/v1/README.md
  api/v1/tetragon/events.pb.go
  api/v1/tetragon/events.proto
  cmd/tetragon/main.go
  contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
  docs/content/en/docs/concepts/events.md
  docs/content/en/docs/reference/grpc-api.md
  install/kubernetes/tetragon/values.yaml
  pkg/bench/bench.go
  pkg/exporter/exporter_test.go
  pkg/fieldfilters/benchmark_test.go
  pkg/fieldfilters/redaction.go
  pkg/fieldfilters/redaction_test.go
  pkg/grpc/exec/exec_test_helper.go
  pkg/grpc/process_manager.go
  pkg/grpc/process_manager_test.go
  pkg/observer/observertesthelper/observer_test_helper.go
  pkg/process/process.go
  pkg/server/server.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
  vendor/google.golang.org/protobuf/internal/msgfmt/format.go
  vendor/google.golang.org/protobuf/reflect/protopath/path.go
  vendor/google.golang.org/protobuf/reflect/protopath/step.go
  vendor/google.golang.org/protobuf/reflect/protorange/range.go
  vendor/modules.txt
Labels: release-note/breaking-changes, release-note/bug

#2325 tetragon: fix redaction filters log message
  cmd/tetragon/main.go
Labels: release-note/misc

#2262 Filter out bash kubernetes healthchecks
  pkg/filters/health_check.go
  pkg/filters/health_check_test.go
Labels: release-note/minor

#2341 Makefile: Do not use $(MAKE) when calling make with `docker run`
  Makefile
Labels: release-note/misc

#2335 docs: fix filename-access example
  docs/content/en/docs/use-cases/filename-access.md
Labels: kind/bug, area/documentation, release-note/docs

#2350 helm: use renovate to update dockerfiles in the Makefile
  install/kubernetes/Makefile
Labels: area/ci, release-note/ci

#2348 tetra: no longer show singular getevents cmd flags as deprecated
  cmd/tetra/getevents/getevents.go
Labels: release-note/misc

#2354 Tetragon e2e Test: Run e2e tests in parallel on multiple runners
  .github/workflows/run-e2e-tests.yaml
  Makefile
Labels: area/ci, release-note/ci

#2340 Add export metrics
  cmd/tetragon/main.go
  docs/content/en/docs/reference/metrics.md
  pkg/exporter/exporter.go
  pkg/exporter/metrics.go
  pkg/metrics/metricsconfig/initmetrics.go
Labels: area/metrics, release-note/minor

#2371 helm: Fix name and selector in operator ServiceMonitor
  install/kubernetes/tetragon/templates/operator_servicemonitor.yaml
Labels: release-note/bug, area/helm

#2373 Refactor metrics label filter logic
  pkg/metrics/consts/consts.go
  pkg/metrics/eventmetrics/eventmetrics.go
  pkg/metrics/labelfilter.go
  pkg/metrics/labels.go
  pkg/metrics/labels_test.go
  pkg/metrics/syscallmetrics/syscallmetrics.go
  pkg/option/config.go
  pkg/option/flags.go
  pkg/option/metricslabels.go
  pkg/option/metricslabels_test.go
  pkg/option/parse.go
Labels: area/metrics, release-note/misc

#2377 docs: explicitly state which regex flavour is used for redaction
  api/v1/README.md
  api/v1/tetragon/events.pb.go
  api/v1/tetragon/events.proto
  contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
  docs/content/en/docs/concepts/events.md
  docs/content/en/docs/reference/grpc-api.md
  install/kubernetes/tetragon/values.yaml
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
Labels: release-note/docs

#2353 docs: update the latest version from the docs with renovate
  .github/renovate.json5
  docs/hugo.toml
Labels: release-note/docs

#2385 Dockerfile: Remove syntax annotation
  Dockerfile.operator
Labels: release-note/misc

#2386 ci: Skip checkpatch for Renovate PRs
  .github/workflows/checkpatch.yaml
Labels: area/ci, release-note/misc

#2392 Prepare for v1.1.0 release
  docs/content/en/docs/reference/helm-chart.md
  docs/hugo.toml
  install/kubernetes/tetragon/Chart.yaml
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/values.yaml
Labels: release-note/misc
