Repository cilium/tetragon, pull requests merged in 2024-05, with the labels that each got.

#2400 proc: set auid to -1 for generated kernel pid 0
  pkg/sensors/exec/procevents/proc_reader.go
Labels: release-note/minor

#2345 TestLabelsDemoApp: Replace isovalent/jobs-app by Opentelemetry demo app
  .github/workflows/run-e2e-tests.yaml
  Makefile
  api/vendor/github.com/cilium/tetragon/pkg/matchers/stringmatcher/stringmatcher.go
  pkg/matchers/stringmatcher/stringmatcher.go
  tests/e2e/tests/labels/labels_test.go
Labels: area/ci, release-note/ci

#2399 bpf: use CORE for execve hook
  bpf/lib/generic.h
  bpf/process/bpf_execve_event.c
Labels: release-note/bug

#2401 Wait for Tetragon's images exist before run test
  .github/workflows/run-e2e-tests.yaml
Labels: release-note/minor, release-note/ci

#2431 Don't create PodInfo if the pod is being deleted
  operator/podinfo/podinfo_controller.go
  operator/podinfo/podinfo_controller_test.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/interceptor/intercept.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/objectutil.go
Labels: release-note/bug, needs-backport/1.0, needs-backport/1.1

#2436 Don't create PodInfo if the pod is being deleted
  operator/podinfo/podinfo_controller.go
  operator/podinfo/podinfo_controller_test.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/interceptor/intercept.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/objectutil.go
Labels: release-note/bug

#2435 Don't create PodInfo if the pod is being deleted
  operator/podinfo/podinfo_controller.go
  operator/podinfo/podinfo_controller_test.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/interceptor/intercept.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/objectutil.go
Labels: release-note/bug

#2433 test: fix TestTraceKernelModule test
  pkg/sensors/tracing/kprobe_test.go
Labels: release-note/minor, needs-backport/1.1

#2432 renovate: add v1.1 in stable branches in config
  .github/renovate.json5
Labels: release-note/ci

#2437 backports:1.1:tests: fix trace module testing
  pkg/sensors/tracing/kprobe_test.go
Labels: release-note/minor

#2455 tetragon: debugging map duplication extending prog/map testers
  pkg/testutils/sensors/load.go
Labels: release-note/ci

#2446 BTF validation fixes
  pkg/btf/validation.go
  pkg/btf/validation_test.go
Labels: release-note/misc

#2457 release_template: also tag API module
  .github/ISSUE_TEMPLATE/release_template.md
Labels: release-note/misc

#2387 Create a Pull Request Template for the project
  .github/pull_request_template.md
Labels: release-note/misc

#2469 helm: Add tetragon.livenessProbe value
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/templates/_container_tetragon.tpl
  install/kubernetes/tetragon/values.yaml
Labels: release-note/minor

#2471 helm: Add tetragon.livenessProbe value
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/templates/_container_tetragon.tpl
  install/kubernetes/tetragon/values.yaml
Labels: release-note/minor

#2468 [v1.1] backport: bpf: use CORE for execve hook
  bpf/lib/generic.h
  bpf/process/bpf_execve_event.c
Labels: release-note/bug

#2476 TracingPolicyStatus: only add error if err not nil
  pkg/sensors/handler.go
Labels: release-note/minor

#2485 tetragon: organize bpf helpers and add a few time related helpers
  bpf/include/api.h
Labels: release-note/misc

#2458 btf: print original error returned by ebpf btf.TypeByName()
  pkg/btf/validation.go
Labels: release-note/minor

#2496 docs: Fix a link in contribution guide
  docs/content/en/docs/contribution-guide/making-changes.md
Labels: area/documentation, release-note/docs

#2494 renovate: switch to get Go version from toolchain directive
  .github/renovate.json5
Labels: release-note/ci
