Repository cilium/tetragon, pull requests merged in 2024-08, with the labels that each got.

#2763 fix: grammar
  docs/content/en/_index.html
Labels: release-note/misc

#2766 doc: update slack channel reference
  .github/lychee.toml
  README.md
  docs/config/_default/hugo.toml
  docs/layouts/partials/footer.html
Labels: area/documentation, release-note/docs

#2774 doc:username: remove empty line to not break api doc
  api/v1/README.md
  api/v1/tetragon/tetragon.pb.go
  api/v1/tetragon/tetragon.proto
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
  docs/content/en/docs/reference/grpc-api.md
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
Labels: release-note/docs

#2782 tetragon: Group missed metrics for policy and attach point
  pkg/metrics/kprobemetrics/collector.go
Labels: release-note/minor

#2781 feat: add home page presentation section
  docs/assets/scss/home.scss
  docs/assets/scss/home/contact.scss
  docs/assets/scss/home/presentation.scss
  docs/content/en/_index.html
  docs/static/images/home/jedi-bee-teacher.png
Labels: area/documentation, release-note/docs

#2790 crd: make followChildren optional
  install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpolicies.yaml
  install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpoliciesnamespaced.yaml
  pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
  pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
  pkg/k8s/apis/cilium.io/v1alpha1/types.go
  pkg/k8s/apis/cilium.io/v1alpha1/version.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go
Labels: release-note/misc

#2765 tetra: fix getevents cmd unexpected timeout
  cmd/tetra/common/client.go
  cmd/tetra/getevents/getevents.go
Labels: release-note/bug

#2793 rthooks: setup do not copy binary twice
  contrib/tetragon-rthooks/cmd/setup/main.go
Labels: release-note/misc

#2795 tetragon: persistent monitoring fixes
  cmd/tetragon/main.go
Labels: release-note/minor

#2797 kprobemetrics: Fix collecting missed metrics
  pkg/metrics/kprobemetrics/collector.go
Labels: kind/bug, area/metrics, release-note/misc

#2804 CI: Changed lint Helm CI trigger
  .github/workflows/lint-helm.yaml
Labels: release-note/ci

#2801 feat: add banner to community meetings and move tetragon slides
  docs/assets/scss/_styles_project.scss
  docs/assets/scss/community-banner.scss
  docs/assets/scss/header.scss
  docs/assets/scss/home.scss
  docs/content/en/_index.html
  docs/layouts/_default/baseof.html
  docs/layouts/partials/community-banner.html
Labels: release-note/docs

#2802 metrics: Expose go_sched_latencies_seconds
  docs/content/en/docs/reference/metrics.md
  pkg/metricsconfig/initmetrics.go
Labels: area/metrics, release-note/minor

#2799 api/ops: Remove MsgOp* constants
  docs/content/en/docs/reference/metrics.md
  pkg/api/ops/ops.go
  pkg/metrics/errormetrics/errormetrics.go
  pkg/metrics/labels.go
  pkg/metrics/opcodemetrics/opcodemetrics.go
Labels: kind/cleanup, release-note/misc

#2796 feat: add Linkedin to the Community Section
  docs/assets/scss/home/hero.scss
  docs/assets/scss/social.scss
  docs/content/en/_index.html
  docs/static/svgs/linkedin-icon.svg
Labels: area/documentation, release-note/docs

#2824 Watcher: fix NODE_NAME if missing
  pkg/watcher/watcher.go
Labels: release-note/misc

#2829 cgidmap: fix initialization bug
  pkg/cgidmap/cgidmap.go
Labels: release-note/minor

#2826 allow to disable the gRPC server
  cmd/tetragon/main.go
  docs/data/tetragon_flags.yaml
  install/kubernetes/tetragon/templates/tetragon_configmap.yaml
  pkg/option/flags.go
Labels: release-note/bug

#2837 CI: Helm lint: Remove pipenv dependency
  .github/workflows/lint-helm.yaml
  install/kubernetes/Makefile
  install/kubernetes/Pipfile
  install/kubernetes/Pipfile.lock
Labels: release-note/ci

#2828 helm: Add tetragon_pod label to metrics via ServiceMonitor
  install/kubernetes/tetragon/templates/servicemonitor.yaml
Labels: area/metrics, release-note/minor, area/helm

#2827 Fix tetragon_process_cache_size metric
  pkg/process/cache.go
  pkg/process/metrics.go
  pkg/process/process.go
Labels: area/metrics, release-note/bug

#2831 fork_test: remove pid export filter
  pkg/sensors/exec/fork_test.go
Labels: release-note/ci

#2840 doc: Improved Tetragon metrics guide
  docs/content/en/docs/installation/metrics.md
Labels: area/documentation, release-note/docs

#2836 helm: use podSecurityContext for rthooks
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/templates/_container_rthooks.tpl
  install/kubernetes/tetragon/values.yaml
Labels: release-note/misc

#2848 [docs] Fix typo
  docs/content/en/docs/installation/runtime-hooks.md
Labels: release-note/docs
