Repository cilium/tetragon, pull requests merged in 2024-10, with the labels that each got.

#2961 Implemented a possibility to disable gops via helm
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/templates/tetragon_configmap.yaml
  install/kubernetes/tetragon/values.yaml
Labels: release-note/minor

#2965 Enabled `tetra` bash autocompletion in the Tetragon image
  Dockerfile
Labels: release-note/minor

#2977 helm: Added dedicated flag for persistent enforcement
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/templates/tetragon_configmap.yaml
  install/kubernetes/tetragon/values.yaml
Labels: release-note/misc, area/helm

#2985 vmtests: use ubuntu-latest
  .github/workflows/vmtests.yml
Labels: area/ci, release-note/ci

#3005 vmtests: install dhclient
  .github/workflows/vmtests.yml
Labels: release-note/ci

#3012 renovate: add v1.2
  .github/renovate.json5
Labels: release-note/misc

#3001 ci:github: retry Test Tetragon on failure
  .github/workflows/packages-e2e-tests.yaml
Labels: release-note/minor

#3023 Export the Notifier interface
  pkg/eventcache/eventcache.go
  pkg/grpc/exec/exec_test_helper.go
  pkg/grpc/process_manager.go
  pkg/server/server.go
Labels: release-note/misc

#3024 Centralize the logic to set node name
  pkg/eventcache/eventcache.go
  pkg/exporter/exporter_test.go
  pkg/grpc/exec/exec.go
  pkg/grpc/process_manager.go
  pkg/grpc/process_manager_test.go
  pkg/grpc/test/test.go
  pkg/grpc/tracing/tracing.go
  pkg/process/process.go
  pkg/ratelimit/ratelimit.go
  pkg/reader/node/node.go
  pkg/reader/node/node_test.go
Labels: release-note/misc

#3029 workflows: fix usage of untrusted input in check links
  .github/workflows/build-images-ci.yml
  .github/workflows/check-links-cron.yaml
  .github/workflows/check-links-pr.yaml
Labels: release-note/ci

#3025 Add an optional cluster_name field to GetEventsResponse
  api/v1/README.md
  api/v1/tetragon/events.pb.go
  api/v1/tetragon/events.proto
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
  docs/content/en/docs/reference/grpc-api.md
  docs/content/en/docs/reference/helm-chart.md
  docs/data/tetragon_flags.yaml
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/templates/tetragon_configmap.yaml
  install/kubernetes/tetragon/values.yaml
  pkg/option/config.go
  pkg/option/flags.go
  pkg/reader/node/node.go
  pkg/reader/node/node_test.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
Labels: release-note/minor

#3030 bpf: enforcer cleanup fix.
  bpf/process/bpf_enforcer.h
Labels: release-note/misc

#3032 tetragon: Make sure lsm programs return bounded value
  bpf/process/bpf_generic_lsm_core.c
  bpf/process/bpf_generic_lsm_output.c
  bpf/process/types/basic.h
Labels: release-note/minor

#3037 tetragon: Fix TestCopyFd test on new v5.10 kernels
  pkg/sensors/tracing/kprobe_copyfd_test.go
Labels: release-note/minor

#3035 version: add version string to metrics
  cmd/tetragon-metrics-docs/metricsmd/metricsmd.go
  docs/content/en/docs/reference/metrics.md
  pkg/version/metrics.go
Labels: release-note/minor

#3042 Remove --expose-kernel-addresses and --pprof-addr flags
  docs/data/tetragon_flags.yaml
  examples/configuration/tetragon.yaml
  pkg/option/flags.go
Labels: kind/cleanup, release-note/minor

#3043 Remove --enable-process-ancestors flag
  docs/data/tetragon_flags.yaml
  examples/configuration/tetragon.yaml
  pkg/option/flags.go
Labels: release-note/minor

#3038 [backport/v1.2] Add support to dump processLRU
  api/v1/README.md
  api/v1/tetragon/sensors.pb.go
  api/v1/tetragon/sensors.pb.json.go
  api/v1/tetragon/sensors.proto
  cmd/tetra/dump/dump.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.pb.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.pb.json.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.proto
  docs/content/en/docs/reference/grpc-api.md
  pkg/grpc/exec/exec.go
  pkg/grpc/exec/kthread_init.go
  pkg/process/cache.go
  pkg/process/process.go
  pkg/server/server.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.pb.json.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.proto
Labels: release-note/misc

#3044 tetra: fix `--policy-names` to apply all event types
  pkg/filters/filters.go
  pkg/filters/policies_test.go
Labels: release-note/minor

#3055 tetragon: Fix TestExitSignal test
  pkg/sensors/exec/exit_test.go
Labels: release-note/minor

#3052 helm: Add part-of and component labels
  install/kubernetes/tetragon/templates/_helpers.tpl
Labels: release-note/minor, area/helm

#3056 policyfilter: do not mark as beta anymore
  docs/data/tetragon_flags.yaml
  pkg/option/flags.go
Labels: release-note/misc

#3059 bpf: remove unused const PossibleCPUSysfsPath
  pkg/bpf/perf_linux.go
Labels: release-note/misc

#3058 update rthooks image to v0.4
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/values.yaml
Labels: release-note/misc
