Repository cilium/tetragon, pull requests merged in 2024-01, with the labels that each got.

#1925 workflows/vmtests: delete artifacts if run was successful
  .github/workflows/vmtests.yml
Labels: area/ci, release-note/ci

#1915 chore: rename TracingPolicy function
  tests/e2e/helpers/grpc/grpc.go
Labels: release-note/misc

#1920 Improve local k8s developer experience
  Makefile
  docs/content/en/docs/contribution-guide/development-setup.md
Labels: release-note/misc

#1904 tetragon: Use cilium/ebpf detection
  pkg/bpf/detect.go
Labels: release-note/minor

#1942 Revert "chore(deps): update all github action artifacts to v4"
  .github/workflows/build-clang-image.yaml
  .github/workflows/build-images-ci.yml
  .github/workflows/build-images-releases.yml
  .github/workflows/gotests.yml
  .github/workflows/run-e2e-tests.yaml
  .github/workflows/vmtests.yml
Labels: area/ci, release-note/ci

#1930 Introduce install/kubernetes/Makefile
  .github/ISSUE_TEMPLATE/release_template.md
  .github/renovate.json5
  .github/workflows/lint-helm.yaml
  install/kubernetes/Makefile
  install/kubernetes/test.sh
Labels: release-note/misc, area/helm

#1944 workflows: bump bom version for race condition fix
  .github/workflows/build-clang-image.yaml
  .github/workflows/build-images-ci.yml
  .github/workflows/build-images-releases.yml
Labels: area/ci, release-note/ci

#1949 metrics: Do not return when we cannot find a _stats map
  pkg/observer/observer_stats.go
Labels: area/metrics, release-note/minor

#1916 chore: unloadpolicy after load
  tests/e2e/tests/policyfilter/policyfilter_test.go
  tests/e2e/tests/skeleton/skeleton_test.go
Labels: release-note/misc

#1827 Add masOS compatibility for 'sed' usage in scripts
  api/export-doc.sh
  docs/content/en/docs/reference/grpc-api.md
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/export-doc.sh
Labels: area/documentation, area/ci, release-note/misc

#1963 Tracepoint tests: Fix comm signedness and length check
  pkg/tracepoint/tracepoint_test.go
Labels: area/testing, release-note/ci

#1962 Actions: add rateLimitScope
  bpf/process/types/basic.h
  docs/content/en/docs/concepts/tracing-policy/selectors.md
  pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
  pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
  pkg/k8s/apis/cilium.io/v1alpha1/types.go
  pkg/k8s/apis/cilium.io/v1alpha1/version.go
  pkg/selectors/kernel.go
  pkg/selectors/kernel_test.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go
Labels: release-note/minor

#1970 workflows: add apt-get update before installs
  .github/workflows/bpf-unit-tests.yml
  .github/workflows/gotests.yml
  .github/workflows/vmtests.yml
Labels: area/ci, release-note/ci

#1958 ci: cross compile the arm tarball for tests
  .github/workflows/packages-e2e-tests.yaml
Labels: release-note/minor

#1972 Dockerfile: bump bpftool revision to 7.3.0
  Dockerfile
Labels: release-note/bug

#1973 docs: fix invalid site param in hugo.toml
  docs/hugo.toml
Labels: area/documentation, release-note/docs

#1923 handling metrics correctly
  pkg/eventcache/eventcache.go
  pkg/grpc/exec/exec.go
  pkg/metrics/errormetrics/errormetrics.go
  pkg/metrics/eventcachemetrics/eventcachemetrics.go
Labels: area/metrics, release-note/minor, area/processcache

#1982 bpf/exec: Move call to read_exe to tail call
  bpf/process/bpf_execve_event.c
Labels: release-note/misc

#1980 docs: improve contribution guide and add a running test page
  docs/content/en/docs/contribution-guide/_index.md
  docs/content/en/docs/contribution-guide/development-setup.md
  docs/content/en/docs/contribution-guide/making-changes.md
  docs/content/en/docs/contribution-guide/running-tests.md
  docs/content/en/docs/contribution-guide/submitting-a-pull-request.md
Labels: area/documentation, release-note/docs

#1979 crd: Fix type mismatch warning
  pkg/watcher/crd/watcher.go
Labels: release-note/misc

#1990 docs: welcome all contributions and add a docs contrib guide
  docs/README.md
  docs/content/en/docs/contribution-guide/_index.md
  docs/content/en/docs/contribution-guide/developer-certificate-of-origin.md
  docs/content/en/docs/contribution-guide/documentation.md
  docs/content/en/docs/contribution-guide/submitting-a-pull-request.md
Labels: area/documentation, release-note/docs

#1991 tetragon: prepare for v1.0.2 release
  docs/hugo.toml
Labels: release-note/minor

#1996 metrics: Do not process the same map multiple times
  pkg/observer/observer_stats.go
Labels: release-note/misc

#2006 docs: fix property naming
  docs/content/en/docs/concepts/tracing-policy/selectors.md
Labels: area/documentation, release-note/docs

#2000 docs: link checker config for docs contributor guide
  .github/lychee.toml
Labels: area/documentation, release-note/docs

#2004 helm: Add `tetragonOperator.enabled` flag to the chart
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/templates/operator_clusterrole.yaml
  install/kubernetes/tetragon/templates/operator_clusterrolebinding.yaml
  install/kubernetes/tetragon/templates/operator_configmap.yaml
  install/kubernetes/tetragon/templates/operator_deployment.yaml
  install/kubernetes/tetragon/templates/operator_service.yaml
  install/kubernetes/tetragon/templates/operator_serviceaccount.yaml
  install/kubernetes/tetragon/templates/operator_servicemonitor.yaml
  install/kubernetes/tetragon/values.yaml
Labels: release-note/minor, area/helm

#1917 fix: fill the missing type in tracingpolicy example
  pkg/tracingpolicy/examples/tracepoint-lseek-pid.yaml
  pkg/tracingpolicy/examples/tracepoint-lseek-test.yaml
Labels: area/testing, release-note/misc

#2026 api:proto: rename Inode to InodeProperties
  api/v1/README.md
  api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
  api/v1/tetragon/tetragon.pb.go
  api/v1/tetragon/tetragon.pb.json.go
  api/v1/tetragon/tetragon.proto
  docs/content/en/docs/reference/grpc-api.md
  pkg/process/process.go
  pkg/sensors/exec/exec_test.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.json.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
Labels: release-note/minor

#2011 vmtests: add 6.6 kernel source
  .github/workflows/vmtests.yml
Labels: release-note/ci

#2038 Git-ignore drop-privileges along with other binaries
  contrib/tester-progs/.gitignore
Labels: release-note/misc

#1919 feat: validate crd versions
  .github/workflows/validate-crd.yaml
Labels: area/ci, release-note/ci

#2031 validation: improve error message when failing to load a TracingPolicy
  pkg/tracingpolicy/generictracingpolicy.go
  pkg/tracingpolicy/generictracingpolicy_test.go
Labels: release-note/minor
