Repository cilium/tetragon, pull requests merged in 2024-07, with the labels that each got.

#2620 [grpc/exec] Do not refinc on a nil parent
  pkg/grpc/exec/kthread_init.go
Labels: release-note/bug

#2549 [backport v1.0] pkg/sensors: reduce stack trace map memory footprint
  bpf/process/types/basic.h
  pkg/sensors/tracing/generickprobe.go
Labels: kind/backport, release-note/bug

#2633 identifies tetragon pod managing a pod
  contrib/k8s-get-tetragon-pod.sh
Labels: release-note/misc

#2638 Provide a way to RewriteConstants in eBPF progs
  pkg/sensors/program/loader.go
  pkg/sensors/program/program.go
Labels: release-note/misc

#2622 helm, doc: Added debug Helm flag for the agent
  docs/content/en/docs/reference/helm-chart.md
  docs/content/en/docs/troubleshooting/_index.md
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/templates/tetragon_configmap.yaml
  install/kubernetes/tetragon/values.yaml
Labels: release-note/minor, area/helm

#2644 feat: update label on hero section on main page
  docs/assets/scss/home/hero.scss
  docs/content/en/_index.html
  docs/static/svgs/logos/cillium.svg
Labels: area/documentation, release-note/docs

#2625 Improve Helm values docs
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/values.yaml
Labels: release-note/docs, area/helm

#2655 rthook: finish renovate config update due to rename
  .github/renovate.json5
Labels: release-note/ci

#2652 backports/1.1: parent binary filter
  api/v1/README.md
  api/v1/tetragon/events.pb.go
  api/v1/tetragon/events.proto
  contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
  docs/content/en/docs/concepts/events.md
  docs/content/en/docs/reference/grpc-api.md
  pkg/filters/binary_regex.go
  pkg/filters/binary_regex_test.go
  pkg/filters/filters.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
Labels: release-note/minor, area/filters

#2653 filters: implement parent binary export filter
  api/v1/README.md
  api/v1/tetragon/events.pb.go
  api/v1/tetragon/events.proto
  contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
  docs/content/en/docs/concepts/events.md
  docs/content/en/docs/reference/grpc-api.md
  pkg/filters/binary_regex.go
  pkg/filters/binary_regex_test.go
  pkg/filters/filters.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
Labels: release-note/minor, area/filters

#2657 Fix linter warnings in Dockerfiles
  Dockerfile
  Dockerfile.dev
  Dockerfile.operator
  Dockerfile.rthooks
  Dockerfile.tarball
  Dockerfile.test
Labels: release-note/misc

#2654 docs: update filename access section of the docs
  docs/content/en/docs/use-cases/filename-access.md
Labels: area/documentation, release-note/docs

#2658 tetragon: small improvement to testing merge sensors
  pkg/testutils/sensors/load.go
Labels: release-note/misc

#2627 [btf] Cleanup AddModulesToSpec
  docs/data/tetragon_flags.yaml
  pkg/btf/btf.go
  pkg/btf/validation.go
  pkg/ksyms/ksyms.go
  pkg/option/config.go
  pkg/option/flags.go
  pkg/sensors/program/loader.go
  pkg/sensors/program/program.go
  pkg/sensors/tracing/generickprobe.go
Labels: release-note/misc

#2659 Fix tetragon build
  pkg/sensors/program/loader.go
Labels: release-note/misc

#2326 helm: Don't give operator permissions to create CRDs if not needed
  install/kubernetes/tetragon/templates/operator_clusterrole.yaml
Labels: release-note/minor, area/helm

#2670 Makefile: Reduce the amount of vendoring calls
  Makefile
Labels: release-note/misc

#2671 docs: improve k8s filtering docs
  docs/content/en/docs/concepts/tracing-policy/k8s-filtering.md
Labels: area/documentation, release-note/docs

#2682 contrib/kind: Make install-tetragon.sh script more portable
  contrib/kind/install-tetragon.sh
Labels: release-note/misc

#2683 Fix the `tetra` CLI install directions for Windows
  docs/content/en/docs/installation/tetra-cli.md
Labels: area/documentation, release-note/docs

#2688 tests/e2e: clone proto event in rpcchecker
  pkg/multiplexer/multiplexer.go
Labels: release-note/ci

#2693 [backport v1.1] pkg/sensors: reduce memory footprint of unused fdinstall maps and various fixes
  bpf/process/types/basic.h
  pkg/sensors/tracing/generickprobe.go
  pkg/sensors/tracing/generictracepoint.go
Labels: kind/backport, release-note/bug

#2694 [backport v1.0] pkg/sensors: reduce memory footprint of unused fdinstall maps
  bpf/process/types/basic.h
  pkg/sensors/tracing/generickprobe.go
  pkg/sensors/tracing/generictracepoint.go
Labels: kind/backport, release-note/bug

#2708 tracing: allow only one of kprobes/tracepoints/lsm
  pkg/sensors/tracing/policyhandler.go
Labels: release-note/misc

#2712 workflows: fix the PR link checker script for `raw` GitHub links
  .github/workflows/check-links-pr.yaml
Labels: area/documentation, area/ci, release-note/ci

#2713 doc: Add docker-buildx to requirements
  docs/content/en/docs/contribution-guide/development-setup.md
Labels: area/documentation, release-note/docs

#2717 update github.com/cilium/ebpf
  go.mod
  go.sum
  pkg/sensors/program/loader.go
  vendor/github.com/cilium/ebpf/CODEOWNERS
  vendor/github.com/cilium/ebpf/btf/btf.go
  vendor/github.com/cilium/ebpf/btf/handle.go
  vendor/github.com/cilium/ebpf/btf/types.go
  vendor/github.com/cilium/ebpf/collection.go
  vendor/github.com/cilium/ebpf/info.go
  vendor/github.com/cilium/ebpf/internal/errors.go
  vendor/github.com/cilium/ebpf/link/xdp.go
  vendor/github.com/cilium/ebpf/map.go
  vendor/github.com/cilium/ebpf/perf/reader.go
  vendor/github.com/cilium/ebpf/prog.go
  vendor/modules.txt
Labels: release-note/dependency

#2705 tetragon: make resolving uid to username work with a processapi struct
  pkg/sensors/exec/exec.go
  pkg/sensors/exec/procevents/proc_reader.go
  pkg/sensors/exec/userinfo/userinfo.go
Labels: release-note/minor

#2707 tetragon: make resolving uid to username work with a processapi struct
  pkg/sensors/exec/exec.go
  pkg/sensors/exec/procevents/proc_reader.go
  pkg/sensors/exec/userinfo/userinfo.go
Labels: release-note/minor

#2664 release_template: also push API tag
  .github/ISSUE_TEMPLATE/release_template.md
Labels: release-note/misc

#2722 proto: Reserve removed field numbers
  api/v1/README.md
  api/v1/tetragon/codegen/helpers/helpers.pb.go
  api/v1/tetragon/events.pb.go
  api/v1/tetragon/events.proto
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
  docs/content/en/docs/reference/grpc-api.md
  vendor/github.com/cilium/tetragon/api/v1/tetragon/codegen/helpers/helpers.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
Labels: release-note/misc

#2726 docs: use $POD env variable in multi node cmd
  docs/content/en/docs/getting-started/execution.md
Labels: area/documentation, release-note/docs

#2736 doc: Minor style improvements in troubleshooting docs
  docs/content/en/docs/troubleshooting/_index.md
Labels: area/documentation, release-note/docs

#2721 Update Getting Started guide
  docs/content/en/docs/getting-started/enforcement.md
  docs/content/en/docs/getting-started/file-events.md
  docs/content/en/docs/getting-started/network.md
  examples/quickstart/network_egress_cluster_enforce.yaml
Labels: area/documentation, release-note/docs

#2735 fix(install-tetragon.sh) fix 'kind load docker-image' in kind setup
  contrib/kind/install-tetragon.sh
Labels: release-note/misc

#2703 tetra: LSM events compact print support
  pkg/encoder/encoder.go
Labels: release-note/minor

#2750 doc: use tag variable for docker-based commands
  docs/content/en/docs/getting-started/enforcement.md
  docs/content/en/docs/getting-started/file-events.md
  docs/content/en/docs/getting-started/install-docker.md
  docs/content/en/docs/getting-started/network.md
Labels: release-note/docs

#2751 Add LoadLSMProgramSimple
  pkg/sensors/program/loader.go
Labels: release-note/misc

#2747 tetragon: only allow single instance to run on a node
  cmd/tetragon/main.go
Labels: release-note/minor

#2589 tetragon: improve systemd deployment detection
  pkg/cgroups/cgroups.go
Labels: release-note/misc

#2757 tetragon: extra debug info on nsid mappings
  pkg/policyfilter/disabled.go
  pkg/policyfilter/policyfilter.go
  pkg/policyfilter/state.go
Labels: release-note/misc

#2723 make: update install/k8s when running "make crds"
  Makefile
  docs/content/en/docs/contribution-guide/making-changes.md
Labels: release-note/misc
