Repository cilium/tetragon, pull requests merged in 2024-06, with the labels that each got.

#2498 helm: Remove deprecated tetragon.skipCRDCreation value
  contrib/upgrade-notes/latest.md
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/values.yaml
Labels: release-note/minor, area/helm

#2488 btf: take first entry on multiple btf validation
  pkg/btf/validation.go
Labels: release-note/minor

#2374 feat: update home page design
  docs/assets/scss/_styles_project.scss
  docs/assets/scss/_variables_project.scss
  docs/assets/scss/button.scss
  docs/assets/scss/footer.scss
  docs/assets/scss/header.scss
  docs/assets/scss/home.scss
  docs/assets/scss/home/cards.scss
  docs/assets/scss/home/contact.scss
  docs/assets/scss/home/cta-banner.scss
  docs/assets/scss/home/diagram.scss
  docs/assets/scss/home/features.scss
  docs/assets/scss/home/hero.scss
  docs/assets/scss/home/share.scss
  docs/assets/scss/home/tabs.scss
  docs/assets/scss/home/title.scss
  docs/assets/scss/home/tools.scss
  docs/assets/scss/home/updates.scss
  docs/assets/scss/home/videos.scss
  docs/assets/scss/social.scss
  docs/content/en/_index.html
  docs/layouts/partials/footer.html
  docs/layouts/shortcodes/tab-code.html
  docs/static/images/diagram-illustration.png
  docs/static/images/home/code-of-conduct-illustration.jpg
  docs/static/images/home/hero-illustration.png
  docs/static/images/home/jedi-bee-sherlock.png
  docs/static/images/home/jedi-bee.png
  docs/static/images/home/share.jpg
  docs/static/svgs/bell-logo.svg
  docs/static/svgs/diagram-illustration-mobile.svg
  docs/static/svgs/diagram-illustration.svg
  docs/static/svgs/frsca-logo.svg
  docs/static/svgs/g-research-logo.svg
  docs/static/svgs/github-icon.svg
  docs/static/svgs/github-logo.svg
  docs/static/svgs/icons/folder-icon.svg
  docs/static/svgs/icons/loop-icon.svg
  docs/static/svgs/icons/monitor-icon.svg
  docs/static/svgs/icons/privacy-icon.svg
  docs/static/svgs/icons/server-icon.svg
  docs/static/svgs/icons/table-icon.svg
  docs/static/svgs/logos/bell-logo.svg
  docs/static/svgs/logos/cncf-logo.svg
  docs/static/svgs/logos/frsca-logo.svg
  docs/static/svgs/logos/g-research-logo.svg
  docs/static/svgs/logos/github-logo.svg
  docs/static/svgs/logos/nationwide-logo.svg
  docs/static/svgs/logos/palantir-logo.svg
  docs/static/svgs/logos/ripple-logo.svg
  docs/static/svgs/nationwide-logo.svg
  docs/static/svgs/palantir-logo.svg
  docs/static/svgs/policies-illustration.svg
  docs/static/svgs/promo-astronomy.svg
  docs/static/svgs/promo-lab.svg
  docs/static/svgs/ripple-logo.svg
  docs/static/svgs/slack-icon.svg
  docs/static/svgs/x-icon.svg
Labels: area/documentation, release-note/docs

#2504 backport:v1.1: btf: take first entry on multiple function matches
  pkg/btf/validation.go
Labels: release-note/minor

#2505 fix: path to og:image
  docs/hugo.toml
Labels: area/documentation, release-note/docs

#2519 Remove Cilium state service cache
  pkg/cilium/monitor.go
  pkg/cilium/state.go
  pkg/oldhubble/cilium/client/client.go
  pkg/oldhubble/cilium/service.go
  pkg/oldhubble/cilium/state.go
  pkg/oldhubble/parser/getters/getters.go
  pkg/oldhubble/servicecache/service_cache.go
Labels: release-note/misc

#2514 renovate: fix Go postUpgradeTasks for stable branches
  .github/renovate.json5
Labels: area/ci, release-note/ci

#2507 docs: updates resources section with newer content
  docs/content/en/docs/resources/_index.md
Labels: area/documentation, release-note/docs

#2522 renovate: group all go updates together and fix a rule
  .github/renovate.json5
Labels: release-note/ci

#2518 Rename NotifyKiller to Enforcer in docs
  docs/content/en/docs/concepts/tracing-policy/selectors.md
Labels: area/documentation, release-note/docs

#2521 tetragon: Remove bpf_globals object
  bpf/Makefile
  bpf/lib/globals.h
  bpf/test/bpf_globals.c
Labels: release-note/minor

#2524 enforcer: fix multiple prog issue with fmod_ret
  pkg/sensors/program/map.go
  pkg/sensors/tracing/enforcer.go
  pkg/sensors/tracing/enforcer_test.go
Labels: release-note/bug, needs-backport/1.1

#2528 [v1.1] enforcer backport
  pkg/sensors/program/map.go
  pkg/sensors/tracing/enforcer.go
  pkg/sensors/tracing/enforcer_test.go
Labels: release-note/bug

#2526 docs: ignore some index.html link from link checker
  .github/lychee.toml
Labels: area/documentation, release-note/ci

#2535 Prepare for v1.1.1 release
  contrib/upgrade-notes/latest.md
  contrib/upgrade-notes/v1.1.1.md
  docs/content/en/docs/reference/helm-chart.md
  docs/hugo.toml
  install/kubernetes/tetragon/Chart.yaml
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/values.yaml
Labels: release-note/misc

#2538 Makefile: exclude api tags from version
  Makefile
Labels: release-note/misc, needs-backport/1.1

#2539 [v1.1] Makefile: exclude api tags from version
  Makefile
Labels: release-note/misc

#2543 Prepare for v1.1.2 release
  contrib/upgrade-notes/v1.1.2.md
  docs/content/en/docs/reference/helm-chart.md
  docs/hugo.toml
  install/kubernetes/tetragon/Chart.yaml
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/values.yaml
Labels: release-note/misc

#2546 pkg/sensors: reduce stack trace map memory footprint
  bpf/process/types/basic.h
  pkg/sensors/tracing/generickprobe.go
Labels: release-note/bug

#2548 [backport v1.1] pkg/sensors: reduce stack trace map memory footprint
  bpf/process/types/basic.h
  pkg/sensors/tracing/generickprobe.go
Labels: kind/backport, release-note/bug

#2555 tetragon: Limit max entries of cgroup_rate_map when it's not used
  bpf/process/bpf_rate.h
  cmd/tetragon/main.go
  pkg/observer/observertesthelper/observer_test_helper.go
  pkg/sensors/base/base.go
Labels: release-note/minor

#2550 syscallinfo: fix typo for oldlstat
  pkg/syscallinfo/syscallnames_amd64.go
Labels: release-note/misc

#2541 [ci/e2e] Uninstall Tetragon after each e2e test
  tests/e2e/install/tetragon/tetragon.go
  tests/e2e/runners/runners.go
Labels: release-note/ci

#2567 docs: fix issues in jq filter examples and broken links
  docs/content/en/docs/concepts/tracing-policy/hooks.md
  docs/content/en/docs/policy-library/observability/_index.md
Labels: area/documentation, release-note/docs

#2578 docs: add more conference videos
  docs/content/en/docs/resources/_index.md
Labels: area/documentation, release-note/docs

#2579 release_template.md: updates
  .github/ISSUE_TEMPLATE/release_template.md
Labels: release-note/misc

#2581 process: Remove ciliumState package variable
  pkg/process/process.go
Labels: release-note/misc

#2583 pkg/sensors: fix for ratelimit_map wrong path pinning
  pkg/sensors/tracing/generickprobe.go
Labels: release-note/misc

#2563 pkg/sensors: reduce memory footprint of unused fdinstall maps and various fixes
  bpf/process/types/basic.h
  pkg/sensors/tracing/generickprobe.go
  pkg/sensors/tracing/generictracepoint.go
Labels: release-note/bug, needs-backport/0.10, needs-backport/1.0, needs-backport/1.1

#2585 tetragon:username: use login name instead of display name
  pkg/reader/userdb/userdb.go
Labels: release-note/minor

#2577 docs: update docs dev deps for security fixes
  docs/package-lock.json
  docs/package.json
Labels: area/documentation, release-note/ci

#2586 backport:1.1:username: use login name instead of display name
  pkg/sensors/exec/exec.go
Labels: release-note/minor

#2607 filters: implement parent binary export filter
  api/v1/README.md
  api/v1/tetragon/events.pb.go
  api/v1/tetragon/events.proto
  contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  contrib/rthooks/tetragon-oci-hook/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
  docs/content/en/docs/concepts/events.md
  docs/content/en/docs/reference/grpc-api.md
  pkg/filters/binary_regex.go
  pkg/filters/binary_regex_test.go
  pkg/filters/filters.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
Labels: release-note/minor, area/filters

#2596 tetragon: fail if --username-metadata receives invalid value
  cmd/tetragon/main.go
  pkg/option/flags.go
Labels: release-note/minor

#2610 Move metrics registry and initialization to pkg/metricsconfig
  cmd/tetra/metrics/print.go
  cmd/tetragon/main.go
  pkg/metrics/metricwithpod_test.go
  pkg/metricsconfig/initmetrics.go
  pkg/metricsconfig/root.go
  pkg/observer/observertesthelper/observer_test_helper.go
Labels: area/metrics, release-note/misc

#2612 tetragon-metrics-docs: Move New function to a separate package
  cmd/tetragon-metrics-docs/main.go
  cmd/tetragon-metrics-docs/metricsmd/metricsmd.go
Labels: release-note/misc

#2616 Fix libbpf submodule checkout in bpftool
  Dockerfile
Labels: release-note/misc, needs-backport/0.10, needs-backport/1.0, needs-backport/1.1

#2618 [backport/v1.0] Fix libbpf submodule checkout in bpftool
  Dockerfile
Labels: release-note/misc

#2617 [backport/v1.1] Fix libbpf submodule checkout in bpftool
  Dockerfile
Labels: release-note/misc
