Repository cilium/tetragon, pull requests merged in 2024-12, with the labels that each got.

#3174 sensors: reduce the logs when {,un}loading policies
  pkg/sensors/load.go
  pkg/sensors/program/map.go
  pkg/sensors/program/program.go
Labels: release-note/minor

#3149 fix(#3148) Update fork-tester.c replace systemd pid with parent process pid
  contrib/tester-progs/fork-tester.c
  pkg/sensors/exec/fork_test.go
Labels: release-note/misc

#3179 ProcessCache: Disable interval test in VM
  pkg/vmtests/skip.go
Labels: release-note/misc

#3181 [sensors] Add optional PostLoadHook
  pkg/sensors/load.go
  pkg/sensors/sensors.go
Labels: release-note/misc

#3185 [backport/v1.2] tetragon: Factor grpc exec events test
  pkg/grpc/exec/exec_test_helper.go
Labels: release-note/misc

#3186 exec: fix tracking of matchBinary children
  bpf/lib/process.h
  bpf/process/bpf_execve_event.c
  pkg/sensors/tracing/matchbinaries_follow_children_test.go
Labels: kind/bug, release-note/bug, needs-backport/1.2

#3197 tetragon: Remove not needed rule commands
  bpf/Makefile
Labels: release-note/minor

#3210 tetragon: setup to let match binary names use args as well
  bpf/lib/process.h
  bpf/process/bpf_execve_event.c
  pkg/api/processapi/processapi.go
Labels: release-note/minor, kind/feature

#3216 docs: use label match in SERVICECIDR command for KinD
  docs/content/en/docs/getting-started/network.md
Labels: area/documentation, release-note/docs

#3217 Aggregate overhead metrics in userspace before reporting
  pkg/metrics/overhead/collector.go
  pkg/metrics/overhead/overhead.go
  pkg/sensors/sensors.go
Labels: area/metrics, release-note/misc

#3219 Prepare for v1.3.0 release
  contrib/upgrade-notes/latest.md
  contrib/upgrade-notes/v1.3.0.md
  docs/config/_default/hugo.toml
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/Chart.yaml
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/values.yaml
Labels: release-note/misc

#3231 docs: Add dev setup instructions for Apple silicon Macs
  docs/content/en/docs/contribution-guide/development-setup.md
Labels: release-note/docs

#3232 [CI] Fix virt-customize issue in vmtests
  cmd/tetragon-vmtests-run/image.go
Labels: release-note/ci

#3237 docs: local dev with Apple Silicon small fixes
  docs/content/en/docs/contribution-guide/development-setup.md
Labels: area/documentation, release-note/docs

#3248 [backport/v1.2][CI] Fix virt-customize issue in vmtests
  cmd/tetragon-vmtests-run/image.go
Labels: release-note/ci

#3247 [backport/v1.3][CI] Fix virt-customize issue in vmtests
  cmd/tetragon-vmtests-run/image.go
Labels: release-note/ci
