Repository cilium/tetragon, pull requests merged in 2024-03, with the labels that each got.

#2158 docs: getting-started k8s fix kind create a cluster
  docs/content/en/docs/getting-started/install-k8s.md
Labels: area/documentation, release-note/docs

#2179 README: add a link to the community call
  README.md
Labels: area/documentation, release-note/docs

#2180 pkg/k8s: fix use of deprecated scripts
  pkg/k8s/Makefile
Labels: release-note/misc

#2186 tetragon-oci-hook: improve logging
  contrib/rthooks/tetragon-oci-hook/cmd/hook/main.go
Labels: release-note/misc

#2135 Loading: Check if probe type is registered
  pkg/sensors/load.go
  pkg/sensors/sensors.go
Labels: release-note/misc

#2196 Tracing: add (minimal) net_device type
  api/v1/README.md
  api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
  api/v1/tetragon/tetragon.pb.go
  api/v1/tetragon/tetragon.pb.json.go
  api/v1/tetragon/tetragon.proto
  bpf/process/types/basic.h
  bpf/process/types/net_device.h
  docs/content/en/docs/reference/grpc-api.md
  examples/tracingpolicy/dev_hard_start_xmit.yaml
  pkg/api/tracingapi/client_kprobe.go
  pkg/btf/validation.go
  pkg/generictypes/generictypes.go
  pkg/grpc/tracing/tracing.go
  pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
  pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
  pkg/k8s/apis/cilium.io/v1alpha1/types.go
  pkg/k8s/apis/cilium.io/v1alpha1/version.go
  pkg/selectors/kernel.go
  pkg/sensors/tracing/args.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.json.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go
Labels: release-note/minor

#2178 tetragon: Remove superfluous switch in HandleMessage callbacks
  pkg/grpc/exec/exec.go
Labels: release-note/minor

#2205 tetragon: update bpf func mappings and add dynptr_*, timer*, ring*
  bpf/include/api.h
  bpf/include/vmlinux.h
Labels: release-note/misc

#2215 make: fix make crds and generate targets
  Makefile
Labels: release-note/minor

#2217 tetragon: update bpf func reserve mapping for proper return value
  bpf/include/api.h
Labels: release-note/misc

#2232 docs: Fix cosign instructions
  docs/content/en/docs/installation/verify.md
Labels: release-note/docs

#2239 bpf: read_call_arg, copy_path once
  bpf/process/types/basic.h
Labels: release-note/misc

#2222 Tracing: add support for file permissions
  api/v1/README.md
  api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
  api/v1/tetragon/tetragon.pb.go
  api/v1/tetragon/tetragon.proto
  bpf/process/types/basic.h
  docs/content/en/docs/reference/grpc-api.md
  pkg/api/tracingapi/client_kprobe.go
  pkg/grpc/tracing/tracing.go
  pkg/reader/path/path.go
  pkg/sensors/tracing/args.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
Labels: release-note/minor

#2228 documentation: more detailed description re FollowFD/UnfollowFD
  docs/content/en/docs/concepts/tracing-policy/selectors.md
Labels: area/documentation, release-note/docs

#2229 e2e: check policy state
  tests/e2e/helpers/grpc/grpc.go
Labels: area/testing, release-note/misc

#2244 tetragon: Implement bpf.GetNumPossibleCPUs through cilium/ebpf library
  pkg/bpf/perf_linux.go
Labels: release-note/minor

#2249 docs: document export filters and fieldfilters
  docs/content/en/docs/concepts/events.md
Labels: release-note/docs

#2259 workflows: check only updated docs links in PRs
  .github/workflows/check-links-pr.yaml
Labels: area/ci, release-note/ci

#2260 observer: remove unused field
  cmd/tetragon/main.go
  pkg/bench/bench.go
  pkg/observer/observer.go
  pkg/observer/observertesthelper/observer_test_helper.go
Labels: release-note/misc

#2243 implement redaction filters
  api/v1/README.md
  api/v1/tetragon/events.pb.go
  api/v1/tetragon/events.pb.json.go
  api/v1/tetragon/events.proto
  cmd/tetragon/main.go
  docs/content/en/docs/concepts/events.md
  docs/content/en/docs/reference/grpc-api.md
  docs/content/en/docs/reference/helm-chart.md
  docs/data/tetragon_flags.yaml
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/templates/tetragon_configmap.yaml
  install/kubernetes/tetragon/values.yaml
  pkg/bench/bench.go
  pkg/exporter/exporter_test.go
  pkg/fieldfilters/redaction.go
  pkg/fieldfilters/redaction_test.go
  pkg/grpc/exec/exec_test_helper.go
  pkg/grpc/process_manager.go
  pkg/grpc/process_manager_test.go
  pkg/observer/observertesthelper/observer_test_helper.go
  pkg/option/flags.go
  pkg/server/server.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.json.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
  vendor/google.golang.org/protobuf/internal/msgfmt/format.go
  vendor/google.golang.org/protobuf/reflect/protopath/path.go
  vendor/google.golang.org/protobuf/reflect/protopath/step.go
  vendor/google.golang.org/protobuf/reflect/protorange/range.go
  vendor/modules.txt
Labels: area/userspace, release-note/major, area/filters
