Repository cilium/tetragon, pull requests merged in 2024-09, with the labels that each got.

#2838 verify.sh: Handle when bpf_verride_return is unavailable
  contrib/verify/verify.sh
Labels: release-note/ci

#2851 docs: Fix the mentioned containerd version
  docs/content/en/docs/concepts/runtime-hooks.md
Labels: release-note/docs

#2858 docs for followChildren true
  docs/content/en/docs/concepts/tracing-policy/selectors.md
Labels: release-note/docs

#2847 CI: Improve/stabilize lint Helm CI workflow
  .github/workflows/lint-helm.yaml
Labels: release-note/ci

#2855 metrics: Expose more errors in tetragon_bpf_missed_events_total counter
  bpf/lib/process.h
  docs/content/en/docs/reference/metrics.md
  pkg/api/processapi/processapi.go
  pkg/metrics/eventmetrics/eventmetrics.go
Labels: area/metrics, release-note/minor

#2863 Replace missing process info metric
  contrib/upgrade-notes/latest.md
  docs/content/en/docs/reference/metrics.md
  pkg/metrics/errormetrics/errormetrics.go
  pkg/metrics/eventmetrics/eventmetrics.go
Labels: area/metrics, kind/cleanup, release-note/minor

#2868 bpf: Fix perf_event_output_metric
  bpf/lib/process.h
Labels: release-note/misc

#2870 bpf: Fix perf_event_output_metric again
  bpf/lib/process.h
Labels: release-note/misc

#2864 renovate: add 'make metrics-docs' to post upgrade cmds
  .github/renovate.json5
Labels: release-note/ci

#2876 Make Debug GRPC call generic
  api/v1/tetragon/sensors.pb.go
  api/v1/tetragon/sensors.proto
  cmd/tetra/loglevel/loglevel.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.pb.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.proto
  pkg/server/server.go
  pkg/server/server_test.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.proto
Labels: release-note/misc

#2859 helm: add an rthooks serviceAccount section
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/templates/rthooks-daemonset.yaml
  install/kubernetes/tetragon/values.yaml
Labels: release-note/misc

#2878 Prepare for v1.2.0 release
  contrib/upgrade-notes/latest.md
  contrib/upgrade-notes/v1.2.0.md
  docs/config/_default/hugo.toml
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/Chart.yaml
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/values.yaml
Labels: release-note/misc

#2889 docs: fix typo
  docs/content/en/docs/installation/runtime-hooks.md
Labels: area/documentation, release-note/docs

#2893 helm: Remove tcp-stats-sample-segs flag from ConfigMap
  install/kubernetes/tetragon/templates/tetragon_configmap.yaml
Labels: kind/cleanup, release-note/misc, area/helm

#2246 Add support to dump processCache
  api/v1/README.md
  api/v1/tetragon/sensors.pb.go
  api/v1/tetragon/sensors.pb.json.go
  api/v1/tetragon/sensors.proto
  cmd/tetra/dump/dump.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.pb.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.pb.json.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.proto
  docs/content/en/docs/reference/grpc-api.md
  pkg/grpc/exec/exec.go
  pkg/grpc/exec/kthread_init.go
  pkg/process/cache.go
  pkg/process/process.go
  pkg/server/server.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.pb.json.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.proto
Labels: release-note/misc

#2899 Fix clone event caching due to missing pod info
  pkg/grpc/exec/exec.go
  pkg/process/process.go
Labels: release-note/bug

#2903 [backport/v1.2][bugfix] Fix clone event caching due to missing pod info
  pkg/grpc/exec/exec.go
  pkg/process/process.go
Labels: release-note/bug

#2910 [v1.1] Fix tetragon_process_cache_size metric
  pkg/process/cache.go
  pkg/process/metrics.go
  pkg/process/process.go
Labels: area/metrics, kind/backport, release-note/bug

#2909 renovate: run make vendor on any Go update
  .github/renovate.json5
Labels: release-note/ci

#2887 chore(docs): rename killer to enforcer
  api/v1/README.md
  api/v1/tetragon/tetragon.pb.go
  api/v1/tetragon/tetragon.proto
  bpf/process/types/basic.h
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
  docs/content/en/docs/reference/grpc-api.md
  install/kubernetes/schemas/tracingpolicy-cilium.io.json
  install/kubernetes/schemas/tracingpolicynamespaced-cilium.io.json
  install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpolicies.yaml
  install/kubernetes/tetragon/crds-yaml/cilium.io_tracingpoliciesnamespaced.yaml
  pkg/api/tracingapi/client_kprobe.go
  pkg/grpc/tracing/tracing.go
  pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
  pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
  pkg/k8s/apis/cilium.io/v1alpha1/tracing_policy_types.go
  pkg/k8s/apis/cilium.io/v1alpha1/version.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/tracing_policy_types.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go
Labels: release-note/misc

#2922 docs: Fix broken links
  docs/content/en/docs/installation/verify.md
Labels: release-note/docs

#2907 helm: Remove deprecated tetragonOperator.skipCRDCreation value
  contrib/upgrade-notes/v1.2.0.md
  install/kubernetes/tetragon/templates/operator_configmap.yaml
Labels: kind/bug, release-note/misc, area/helm, needs-backport/1.2

#2925 tetragon: probe_read usage may cause issues with newer kernels
  bpf/include/api.h
  bpf/lib/bpf_cgroup.h
  bpf/lib/bpf_task.h
Labels: release-note/misc

#2897 Minor cleanup of Helm Makefile
  install/kubernetes/Makefile
Labels: kind/cleanup, release-note/misc, area/helm

#2924 [v1.2] helm: Remove deprecated tetragon.skipCRDCreation value
  contrib/upgrade-notes/v1.2.0.md
  install/kubernetes/tetragon/templates/operator_configmap.yaml
Labels: release-note/bug, area/helm

#2888 observer: Collect ring buffer metrics only once
  pkg/observer/observer.go
Labels: release-note/misc

#2931 helm: Set rthooks.podSecurityContext to empty by default
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/values.yaml
Labels: release-note/misc, needs-backport/1.2

#2936 [jsonchecker] Remove const from parameters
  pkg/jsonchecker/jsonchecker.go
Labels: release-note/misc

#2934 helm: Set rthooks.podSecurityContext to empty by default
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/values.yaml
Labels: kind/backport, release-note/misc

#2944 tetragon: Fix map PinPath setup in case the map is shared
  pkg/sensors/load.go
Labels: release-note/minor

#2908 Added metrics for LRU data cache
  docs/content/en/docs/reference/metrics.md
  pkg/observer/cache.go
  pkg/observer/data.go
  pkg/observer/metrics.go
Labels: area/metrics, release-note/minor

#2949 Add support to exclude valid processes from dump processCache
  api/v1/README.md
  api/v1/tetragon/sensors.pb.go
  api/v1/tetragon/sensors.proto
  cmd/tetra/dump/dump.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.pb.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.proto
  docs/content/en/docs/reference/grpc-api.md
  pkg/process/cache.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.proto
Labels: release-note/misc

#2904 [backport/v1.1][bugfix] Fix clone event caching due to missing pod info
  pkg/grpc/exec/exec.go
  pkg/process/process.go
Labels: release-note/bug

#2905 [backport/v1.0][bugfix] Fix clone event caching due to missing pod info
  pkg/grpc/exec/exec.go
  pkg/process/process.go
Labels: release-note/bug

#2932 Improve rthooks docs
  docs/content/en/docs/installation/runtime-hooks.md
Labels: release-note/docs

#2952 tetragon: Factor grpc exec events test
  pkg/grpc/exec/exec_test_helper.go
Labels: release-note/minor

#2948 bpf: allow all operations for syscall64 type
  bpf/process/types/basic.h
Labels: release-note/minor, needs-backport/1.2

#2929 Examples: Add TCP listen example tracing policy
  examples/tracingpolicy/tcp-listen.yaml
Labels: release-note/misc

#2918 Makefile: run vendor in contrib/tetragon-rthooks on protogen
  Makefile
Labels: release-note/misc
