Repository cilium/tetragon, pull requests merged in 2024-11, with the labels that each got.

#3064 doc: Removed old matchBinaries limitation
  docs/content/en/docs/concepts/tracing-policy/selectors.md
Labels: release-note/docs

#3031 workflows: simplify build image CI
  .github/workflows/build-images-ci.yml
Labels: release-note/ci

#3074 [metrics] Fix overhead_program metrics for return probes
  docs/content/en/docs/reference/metrics.md
  pkg/metrics/overhead/collector.go
  pkg/metrics/overhead/overhead.go
  pkg/sensors/sensors.go
Labels: release-note/bug

#3076 enforcer: add policynamespace to sensor
  pkg/sensors/tracing/enforcer.go
Labels: release-note/misc

#3077 Renovate: Extend Helm files coverage
  .github/renovate.json5
Labels: release-note/ci

#3083 [docs] Fix typo
  docs/content/en/docs/installation/runtime-hooks.md
Labels: release-note/docs

#3105 Backports/v1.2: tetragon: probe_read usage may cause issues with newer kernels
  bpf/include/api.h
  bpf/lib/bpf_cgroup.h
  bpf/lib/bpf_task.h
Labels: release-note/misc

#3139 workflows: only run cron jobs on main repo
  .github/workflows/check-links-cron.yaml
  .github/workflows/renovate.yaml
Labels: area/ci, release-note/ci

#3141 tetragon: Unflake the TestGeneratedExecEvents test
  cmd/tetragon/main_test.go
Labels: release-note/minor

#3146 cgrouprate: refactor code for registering into base
  cmd/tetragon/main.go
  pkg/cgrouprate/bpf.go
  pkg/cgrouprate/cgrouprate.go
  pkg/cgrouprate/cgrouprate_test.go
  pkg/cgrouprate/sensor.go
  pkg/observer/observertesthelper/observer_test_helper.go
  pkg/sensors/base/base.go
  pkg/sensors/base/extensions.go
  pkg/sensors/base/utils.go
Labels: release-note/misc

#3155 filters: implement parent_arguments_regex
  api/v1/README.md
  api/v1/tetragon/events.pb.go
  api/v1/tetragon/events.proto
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
  docs/content/en/docs/concepts/events.md
  docs/content/en/docs/reference/grpc-api.md
  pkg/filters/arguments_regex.go
  pkg/filters/arguments_regex_test.go
  pkg/filters/filters.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
Labels: release-note/minor, area/filters

#3157 backports/v1.2: filters: implement parent_arguments_regex
  api/v1/README.md
  api/v1/tetragon/events.pb.go
  api/v1/tetragon/events.proto
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
  docs/content/en/docs/concepts/events.md
  docs/content/en/docs/reference/grpc-api.md
  pkg/filters/arguments_regex.go
  pkg/filters/arguments_regex_test.go
  pkg/filters/filters.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
Labels: release-note/minor, area/filters

#3103 feat: develop Tetragon Enterprise page
  docs/assets/scss/home.scss
  docs/assets/scss/home/distribution.scss
  docs/assets/scss/home/hero.scss
  docs/assets/scss/social.scss
  docs/config/_default/hugo.toml
  docs/content/en/_index.html
  docs/content/en/enterprise.html
  docs/layouts/shortcodes/social.html
  docs/static/images/enterprise/eol.svg
  docs/static/images/enterprise/hero-illustration.png
  docs/static/images/enterprise/isovalent.svg
  docs/static/images/enterprise/security.svg
  docs/static/images/enterprise/support.svg
  docs/static/svgs/github-icon.svg
  docs/static/svgs/linkedin-icon.svg
  docs/static/svgs/slack-icon.svg
  docs/static/svgs/social/github-icon.svg
  docs/static/svgs/social/lab-icon.svg
  docs/static/svgs/social/linkedin-icon.svg
  docs/static/svgs/social/slack-icon.svg
  docs/static/svgs/social/x-icon.svg
  docs/static/svgs/x-icon.svg
Labels: area/documentation, release-note/docs

#3169 release: Fix checkout to the correct branch before tagging
  .github/ISSUE_TEMPLATE/release_template.md
Labels: release-note/misc
