Repository cilium/tetragon, pull requests merged in 2024-02, with the labels that each got.

#2059 Fix typo on TracingPolicy Selectors Stack Traces documentation
  docs/content/en/docs/concepts/tracing-policy/selectors.md
Labels: release-note/docs

#2045 workflows: use defined actions/checkout version in validate-crd.yaml
  .github/workflows/validate-crd.yaml
Labels: release-note/ci

#2064 bpf: document how to use read_exe()
  bpf/process/bpf_execve_event.c
Labels: release-note/misc

#2072 tests: add debug message to TestProcessSetCap
  contrib/tester-progs/change-capabilities.c
  pkg/sensors/tracing/kprobe_test.go
Labels: release-note/minor

#2075 tetragon: Harden TestMatchCloneThreadsIDs test
  pkg/sensors/exec/threads_test.go
Labels: release-note/minor

#2096 pkg/metrics: fix a typo in `policyfilter_metrics_total`
  pkg/metrics/policyfiltermetrics/policyfiltermetrics.go
Labels: area/metrics, release-note/misc

#2104 README: remove the link to the tutorials in docs
  README.md
Labels: area/documentation, release-note/docs

#2108 renovate: include all Dockerfiles, even the one with prefix
  .github/renovate.json5
Labels: release-note/ci

#1986 tetragon: extract linux_binprm member using CO:RE
  api/v1/README.md
  api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
  api/v1/tetragon/tetragon.pb.go
  api/v1/tetragon/tetragon.pb.json.go
  api/v1/tetragon/tetragon.proto
  bpf/process/types/basic.h
  docs/content/en/docs/reference/grpc-api.md
  examples/tracingpolicy/security_bprm_check.yaml
  pkg/api/tracingapi/client_kprobe.go
  pkg/btf/validation.go
  pkg/generictypes/generictypes.go
  pkg/grpc/tracing/tracing.go
  pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
  pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
  pkg/k8s/apis/cilium.io/v1alpha1/types.go
  pkg/k8s/apis/cilium.io/v1alpha1/version.go
  pkg/selectors/kernel.go
  pkg/sensors/tracing/args.go
  pkg/sensors/tracing/kprobe_test.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/codegen/eventchecker/eventchecker.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.json.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpolicies.yaml
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_tracingpoliciesnamespaced.yaml
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go
Labels: release-note/minor

#2091 chore: Sync bpf_tracing.h
  bpf/libbpf/bpf_tracing.h
Labels: release-note/misc

#2119 exporter: fix hang when exporter fails to start
  pkg/server/server.go
Labels: area/userspace, release-note/bug

#2084 Update enforcement.md
  docs/content/en/docs/getting-started/enforcement.md
Labels: area/documentation, release-note/docs

#1952 policyfilter: add a label that allows to filter based on namespaces
  pkg/labels/labels.go
  pkg/labels/labels_test.go
  pkg/policyfilter/state.go
Labels: release-note/minor

#2126 renovate: match all Makefiles
  .github/renovate.json5
Labels: release-note/ci

#2123 Set node_name to hostname if NODE_NAME envvar is not found
  pkg/grpc/process_manager_test.go
  pkg/reader/node/node.go
Labels: kind/bug, release-note/bug

#2129 backports/v0.10: Set node_name to hostname if NODE_NAME envvar is not found
  pkg/grpc/process_manager_test.go
  pkg/reader/node/node.go
Labels: kind/backport

#2127 exporter: return err when exporter fails to start
  cmd/tetragon/main.go
  pkg/bench/bench.go
  pkg/exporter/exporter.go
  pkg/exporter/exporter_test.go
  pkg/observer/observertesthelper/observer_test_helper.go
Labels: release-note/minor

#2148 tetragon:trivial: create run dir early to avoid errors
  cmd/tetragon/main.go
Labels: release-note/minor

#2154 ci: only check docs on PR to main
  .github/workflows/build-deploy-docs.yaml
  .github/workflows/check-links-pr.yaml
Labels: release-note/ci

#2144 Remove unused PodInfo utility functions
  pkg/observer/observertesthelper/observer_test_helper.go
  pkg/watcher/fake.go
  pkg/watcher/fake_test.go
  pkg/watcher/watcher.go
  pkg/watcher/watcher_test.go
Labels: release-note/minor

#2153 cmd/tetra: remove tp_state_ prefix in state in tp list
  cmd/tetra/tracingpolicy/tracingpolicy.go
Labels: release-note/misc

#2115 docs: tetragon troubleshoot improve
  docs/content/en/docs/troubleshooting/_index.md
Labels: area/documentation, release-note/docs

#2125 docs: Privileged execution - use nginx instead of test-pod image
  docs/content/en/docs/use-cases/process-lifecycle/privileged-execution.md
  testdata/specs/testpod.yaml
Labels: release-note/minor, release-note/docs

#2166 tetragon: Move enforcer-tester to .gitignore
  contrib/tester-progs/.gitignore
Labels: release-note/misc
