Repository cilium/tetragon, pull requests merged in 2025-01, with the labels that each got.

#3256 docs: remove redundance CLI command in tracing policy example
  docs/content/en/docs/concepts/tracing-policy/example.md
Labels: area/documentation, release-note/docs

#3281 [v1.3] ci: remove buildjet runners and use GitHub arm64 runners
  .github/workflows/build-images-releases.yml
Labels: area/ci, release-note/ci

#3280 ci: remove buildjet runners and use GitHub arm64 runners
  .github/workflows/build-images-releases.yml
Labels: area/ci, release-note/ci

#3283 [v1.1] ci: remove buildjet runners and use GitHub arm64 runners
  .github/workflows/build-images-releases.yml
Labels: area/ci, release-note/ci

#3286 renovate: fix for config change 70ad4e78d5b4
  .github/renovate.json5
Labels: area/ci, release-note/ci

#3267 fix: nspid assign is not correct
  bpf/cgroup/bpf_cgroup_events.h
  bpf/lib/bpf_task.h
  bpf/process/bpf_execve_event.c
  bpf/process/bpf_fork.c
Labels: release-note/minor

#3261 bug: fix assign vfsmnt correctly
  bpf/process/bpf_process_event.h
Labels: release-note/minor

#3111 fix: correcting the script path for minikube installation steps in do…
  docs/content/en/docs/concepts/tracing-policy/k8s-filtering.md
Labels: area/documentation, release-note/docs

#3289 fix: improve error handling for tracing policies directory access
  cmd/tetragon/main.go
Labels: release-note/misc

#3124 tetra: Add CEL filter to the CLI
  cmd/tetra/getevents/getevents.go
  cmd/tetra/getevents/getevents_test.go
  pkg/filters/filters.go
  pkg/filters/filters_test.go
Labels: release-note/minor

#3305 tetragon: add get_current_task_btf
  bpf/include/api.h
Labels: release-note/misc

#3303 Add Tetragon talk from Kubecon NA
  docs/content/en/docs/resources/_index.md
Labels: area/documentation, release-note/docs

#3307 bpf: declare maps with __type for key and value
  bpf/process/addr_lpm_maps.h
  bpf/process/argfilter_maps.h
  bpf/process/bpf_execve_event.c
  bpf/process/bpf_generic_kprobe.c
  bpf/process/bpf_generic_lsm_core.c
  bpf/process/bpf_generic_retkprobe.c
  bpf/process/bpf_generic_tracepoint.c
  bpf/process/bpf_generic_uprobe.c
  bpf/process/policy_filter.h
  bpf/process/string_maps.h
  bpf/process/types/basic.h
Labels: area/bpf, release-note/misc

#3284 doc: note that kernels >= 6.11 require new cgroupv1 configs
  docs/content/en/docs/installation/faq.md
Labels: release-note/minor, release-note/docs

#3322 clang-format: use ignore file
  .clang-format-ignore
  .github/workflows/static-checks.yaml
  Makefile
Labels: release-note/misc

#3324 renovate: remove matchBaseBranches on main for grouping rules
  .github/renovate.json5
Labels: release-note/ci

#3325 fix: Troubleshooting documentation for System dump
  docs/content/en/docs/troubleshooting/sysdump.md
Labels: area/documentation, release-note/docs

#3334 docs: fix typo referencing kube-system as kubesystem
  docs/content/en/docs/getting-started/enforcement.md
  docs/content/en/docs/getting-started/file-events.md
  docs/content/en/docs/getting-started/network.md
Labels: release-note/docs

#3335 tetra: Set default for retries to 1
  cmd/tetra/main.go
Labels: release-note/minor

#3343 tetra/debug: Clone GetDebugResponse entries
  pkg/process/cache.go
Labels: release-note/misc, needs-backport/1.2, needs-backport/1.3

#3249 [backport/v1.1][CI] Fix virt-customize issue in vmtests
  cmd/tetragon-vmtests-run/image.go
Labels: release-note/ci

#3344 [backport/v1.3] tetra/debug: Clone GetDebugResponse entries
  pkg/process/cache.go
Labels: release-note/misc

#3345 [backport/v1.2] tetra/debug: Clone GetDebugResponse entries
  pkg/process/cache.go
Labels: release-note/misc

#3348 Add the ability to get process cache entries
  pkg/process/cache.go
  pkg/process/process.go
Labels: release-note/misc

#3349 [backport/v1.3] Add the ability to get process cache entries
  pkg/process/cache.go
  pkg/process/process.go
Labels: release-note/misc

#3350 [backport/v1.2] Add the ability to get process cache entries
  pkg/process/cache.go
  pkg/process/process.go
Labels: release-note/misc

#3347 pkg/sensors: RawDetachUnloader do not detach on unpin false
  pkg/sensors/unloader/unloader.go
Labels: release-note/bug

#3352 pkg/sensors: pin link in TracingAttach
  pkg/sensors/program/loader.go
Labels: release-note/misc

#3354 CI: build tetragon on every commit of a PR
  .github/workflows/static-checks.yaml
Labels: release-note/ci

#3356 vmtests: disable TestFastK8s
  pkg/vmtests/skip.go
Labels: release-note/misc
