Repository cilium/tetragon, pull requests merged in 2025-05, with the labels that each got.

#3679 k8s: Let controller-runtime manage the pod informer
  .github/workflows/integration-test.yaml
  cmd/tetragon/main.go
  pkg/manager/manager.go
  pkg/manager/manager_integration_test.go
  pkg/watcher/deleted_pod_cache.go
  pkg/watcher/pod.go
  pkg/watcher/pod_test.go
Labels: release-note/misc

#3676 tetragon: Allow uprobes to use actions
  pkg/sensors/tracing/genericuprobe.go
Labels: release-note/minor

#3693 loaderCache: copy map spec before using it
  pkg/sensors/load_linux.go
Labels: kind/bug, release-note/misc

#3690 watcher: Remove unused AddPodInformer function
  pkg/process/podinfo_test.go
  pkg/watcher/pod.go
  pkg/watcher/pod_test.go
Labels: release-note/misc

#3689 test: Remove duplicate fake k8s watcher
  pkg/observer/observertesthelper/observer_test_helper.go
Labels: release-note/misc

#3700 [v1.2] values: update rthooks image to 0.5
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/values.yaml
Labels: release-note/misc

#3688 tetragon: Fix check_cap tester program call
  contrib/tester-progs/sigkill-unprivileged-user-ns-tester.c
Labels: release-note/minor

#3713 Feature pages nits
  docs/content/en/features/network-observability.md
  docs/content/en/features/operating-system-integrity.md
  docs/content/en/features/privileges-monitoring.md
Labels: release-note/misc

#3699 doc: fix cgroup rate explanation not match the parameter
  docs/content/en/docs/concepts/cgroup-rate.md
Labels: release-note/docs

#3733 policyfilter/e2e: Fix e2e tests
  tests/e2e/tests/policyfilter/policyfilter_test.go
Labels: release-note/ci

#3737 tetragon: fix resolve issue with argument order
  pkg/sensors/tracing/generickprobe.go
  pkg/sensors/tracing/kprobe_test.go
Labels: release-note/bug, needs-backport/1.4

#3739 1.4 backports
  pkg/sensors/tracing/generickprobe.go
  pkg/sensors/tracing/kprobe_test.go
Labels: release-note/backport

#3740 Temporarily disable controller-runtime metrics
  pkg/manager/manager.go
  pkg/manager/manager_integration_test.go
Labels: release-note/misc

#3735 tetragon/windows: Add Multiple program attach types
  pkg/sensors/program/loader_windows.go
Labels: release-note/misc

#3694 vmtests CI: avoid running duplicate tests
  pkg/vmtests/list.go
  tools/split-tetragon-gotests/main.go
Labels: release-note/ci

#3673 docs: update homepage announcement section
  docs/content/en/_index.html
Labels: release-note/docs

#3748 tetragon/windows: Fix exec/exit event timestamp in event json
  bpf/windows/process_monitor.c
  pkg/ktime/ktime_windows.go
  pkg/ktime/ktime_windows_test.go
  pkg/sensors/exec/procevents/proc_reader_windows.go
Labels: release-note/misc

#3759 Add node_labels field to Tetragon events
  api/v1/README.md
  api/v1/tetragon/events.pb.go
  api/v1/tetragon/events.proto
  cmd/tetragon/main.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
  docs/content/en/docs/reference/grpc-api.md
  install/kubernetes/tetragon/templates/clusterrole.yaml
  pkg/manager/manager.go
  pkg/manager/manager_integration_test.go
  pkg/reader/node/node.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
Labels: release-note/minor

#3786 refactor: Rename functions in the node package
  cmd/tetragon/main.go
  pkg/manager/manager.go
  pkg/manager/manager_integration_test.go
  pkg/reader/node/node.go
  pkg/reader/node/node_test.go
Labels: release-note/misc
