Repository cilium/tetragon, pull requests merged in 2025-04, with the labels that each got.

#3560 tetragon/windows: Port reader/proc package on Windows
  pkg/reader/proc/proc.go
  pkg/reader/proc/proc_linux.go
  pkg/reader/proc/proc_test_linux.go
  pkg/reader/proc/proc_test_windows.go
  pkg/reader/proc/proc_windows.go
Labels: release-note/misc

#3547 tetragon/widows: Add signal translation for Windows
  pkg/reader/exec/signal_windows.go
Labels: release-note/minor

#3573 tetragon/windows: Port cmd/tetra binary into Windows
  cmd/tetra/cgtracker/cgtracker_windows.go
  cmd/tetra/debug/debug_windows.go
  cmd/tetra/tracingpolicy/generate/all_syscalls.go
  cmd/tetra/tracingpolicy/generate/all_syscalls_windows.go
  cmd/tetra/tracingpolicy/generate/generate.go
Labels: release-note/minor

#3575 tetragon/windows: Port process cache package on Windows
  pkg/process/process.go
  pkg/process/process_id_linux.go
  pkg/process/process_id_windows.go
Labels: release-note/misc

#3577 tetragon/windows: Support Windows create and exit process - observer changes
  pkg/observer/observer.go
  pkg/observer/observer_linux.go
  pkg/observer/observer_windows.go
Labels: release-note/major

#3580 podinfo: Add spec.nodeName field
  install/kubernetes/tetragon/crds-yaml/cilium.io_podinfo.yaml
  operator/podinfo/podinfo_controller.go
  operator/podinfo/podinfo_controller_test.go
  pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_podinfo.yaml
  pkg/k8s/apis/cilium.io/v1alpha1/types.go
  pkg/k8s/apis/cilium.io/v1alpha1/version.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/client/crds/v1alpha1/cilium.io_podinfo.yaml
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/types.go
  vendor/github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1/version.go
Labels: release-note/misc

#3526 ci: In "Tetragon Go Test" add vmlinux in artifact when test fails
  .github/workflows/gotests.yml
Labels: release-note/ci

#3578 tetragon/windows: Support Windows create and exit process - sensor changes
  pkg/sensors/base/base.go
  pkg/sensors/base/base_linux.go
  pkg/sensors/base/base_windows.go
  pkg/sensors/config/confmap/confmap.go
  pkg/sensors/load.go
  pkg/sensors/load_linux.go
  pkg/sensors/load_windows.go
  pkg/sensors/program/loader.go
  pkg/sensors/program/loader_linux.go
  pkg/sensors/program/loader_windows.go
Labels: release-note/major

#3603 watcher: Watch namespaces
  cmd/tetragon/main_linux.go
  install/kubernetes/tetragon/templates/clusterrole.yaml
  pkg/watcher/namespace.go
  pkg/watcher/namespace_test.go
Labels: release-note/misc

#3609 Fix discrepancy between export and k8s node name
  pkg/exporter/exporter_test.go
  pkg/grpc/process_manager_test.go
  pkg/reader/node/node.go
  pkg/reader/node/node_test.go
  pkg/watcher/watcher.go
Labels: release-note/bug, needs-backport/1.2, needs-backport/1.3, needs-backport/1.4

#3610 1.4 backports
  pkg/exporter/exporter_test.go
  pkg/grpc/process_manager_test.go
  pkg/reader/node/node.go
  pkg/reader/node/node_test.go
  pkg/watcher/watcher.go
Labels: release-note/backport

#3616 Restore proc_test.go files
  pkg/reader/proc/proc_linux_test.go
  pkg/reader/proc/proc_windows_test.go
Labels: release-note/misc

#3618 tetragon/windows: Port Unit Tests in cmd/tetragon on Windows
  cmd/tetragon/main_test.go
  pkg/constants/constants_linux.go
  pkg/constants/constants_windows.go
  pkg/testutils/filenames.go
Labels: release-note/misc

#3620 tetragon/windows: Exclude some unit tests for Windows
  pkg/alignchecker/alignchecker_test.go
  pkg/bugtool/maps_test.go
  pkg/cgrouprate/cgrouprate_test.go
  pkg/metrics/metricwithpod_test.go
  pkg/policyfilter/map_test.go
  pkg/policyfilter/state_test.go
  pkg/server/addr_test.go
  pkg/tracepoint/tracepoint_test.go
Labels: release-note/misc

#3622 tetragon/windows: Port reader unit tests into Windows
  pkg/reader/path/path_linux_test.go
  pkg/reader/path/path_windows_test.go
  pkg/reader/userdb/userdb_linux_test.go
  pkg/reader/userdb/userdb_windows_test.go
Labels: release-note/misc

#3621 tetragon/windows: Port unit tests in grpc package into Windows
  pkg/grpc/exec/exec_test.go
  pkg/grpc/exec/exec_test_linux.go
  pkg/grpc/process_manager_test.go
  pkg/grpc/process_manager_test_linux.go
  pkg/grpc/process_manager_test_windows.go
Labels: release-note/misc

#3611 tetragon/windows: Add windows compile as a ci step
  .github/workflows/static-checks.yaml
Labels: release-note/ci

#3626 doc: update export filtering example
  docs/content/en/docs/concepts/events.md
Labels: area/documentation, release-note/docs

#3636 tetragon: Fix storing of flags and mode for path
  bpf/process/types/basic.h
Labels: release-note/minor

#3635 tetragon: Fix storing of flags and mode for path
  bpf/process/types/basic.h
Labels: release-note/minor

#3634 tetragon: Fix storing of flags and mode for path
  bpf/process/types/basic.h
Labels: release-note/minor

#3638 go.mod: Consistently add replace directives
  api/go.mod
  api/vendor/modules.txt
  contrib/tetragon-rthooks/go.mod
  contrib/tetragon-rthooks/vendor/modules.txt
Labels: release-note/misc

#3641 doc: add events.proto link for event filters
  docs/content/en/docs/concepts/events.md
Labels: release-note/docs

#3650 observertesthelper: Remove unused crd option
  pkg/observer/observertesthelper/observer_test_helper.go
Labels: release-note/misc

#3643 Use controller-runtime manager to access namespaces
  .github/workflows/integration-test.yaml
  cmd/tetragon/main.go
  pkg/manager/manager.go
  pkg/manager/manager_integration_test.go
  pkg/watcher/namespace.go
  pkg/watcher/namespace_test.go
Labels: release-note/misc

#3651 Get tracing policy informers from controller-runtime manager
  cmd/tetragon/main.go
  pkg/manager/manager.go
  pkg/watcher/crdwatcher/tracingpolicy.go
Labels: release-note/misc

#3640 docs: improve features pages copy
  docs/content/en/features/capabilities-monitoring.md
  docs/content/en/features/execution-monitoring.md
  docs/content/en/features/file-integrity-monitoring.md
  docs/content/en/features/kubernetes-identity-aware-policies.md
  docs/content/en/features/network-observability.md
  docs/content/en/features/operating-system-integrity.md
  docs/content/en/features/privileges-monitoring.md
  docs/layouts/features/single.html
Labels: release-note/docs

#3663 examples: use explicit wording about guarantees
  examples/README.md
  examples/tracingpolicy/hardlink-observe.yaml
  examples/tracingpolicy/hardlink-override.yaml
  examples/tracingpolicy/openat_write.yaml
  examples/tracingpolicy/symlink-observe.yaml
  examples/tracingpolicy/symlink-override.yaml
Labels: release-note/docs

#3645 tetragon/windows: Build windows bpf program and smoke test tetragon
  .github/workflows/windows-build-smoke-test.yml
  install/windows/README.md
  install/windows/setup-windows.ps1
Labels: release-note/ci

#3666 GetCgroupIdFromPath: add path to error
  pkg/cgroups/cgroups_linux.go
Labels: release-note/misc

#3661 PodInfo: Add .process.pod.container.privileged field
  api/v1/README.md
  api/v1/tetragon/tetragon.pb.go
  api/v1/tetragon/tetragon.pb.json.go
  api/v1/tetragon/tetragon.proto
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.json.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
  docs/content/en/docs/reference/grpc-api.md
  pkg/grpc/process_manager_test.go
  pkg/process/podinfo.go
  pkg/process/podinfo_test.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.json.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
Labels: release-note/minor

#3657 Refactor waitCRDs function
  cmd/tetragon/main.go
  pkg/manager/manager.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/apiextensions/v1/interface.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/listers/apiextensions/v1/expansion_generated.go
  vendor/modules.txt
Labels: release-note/misc

#3675 helm: Change default metrics scrape interval to 60s
  contrib/upgrade-notes/latest.md
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/values.yaml
Labels: release-note/minor, area/helm

#3678 doc: fix policy-library sshd anchor link & title
  docs/content/en/docs/policy-library/observability/_index.md
Labels: release-note/docs

#3684 docs: update rthooks installation
  docs/content/en/docs/installation/runtime-hooks.md
Labels: release-note/docs
