Repository cilium/tetragon, pull requests merged in 2025-09, with the labels that each got.

#3948 Optimize Kprobe Rate Limit Test Performance
  pkg/sensors/tracing/kprobe_test.go
Labels: release-note/misc

#4060 k8s: Reduce RBAC permission for non-k8s deployment
  cmd/tetragon/main.go
  pkg/manager/manager.go
  pkg/option/config.go
  pkg/watcher/conf/conf.go
Labels: release-note/minor

#4094 docs: fix the yaml indent in selector semantics
  docs/content/en/docs/concepts/tracing-policy/selectors.md
Labels: release-note/docs

#4107 policy_stats: use the map only for policy sensors
  bpf/lib/policy_stats.h
  bpf/lib/process.h
  bpf/process/bpf_generic_tracepoint.c
  bpf/process/generic_calls.h
Labels: release-note/misc

#4116 k8s: Add alias for getting k8s config
  pkg/watcher/conf/conf.go
Labels: release-note/misc

#4126 tetragon: Fix struct perf_event_info_type layout
  bpf/process/types/perfevent.h
  pkg/api/tracingapi/client_kprobe.go
Labels: release-note/minor

#4128 Fix flaky downloads of eBPF for Windows deps
  .github/workflows/windows-build-smoke-test.yml
Labels: release-note/ci

#4123 doc: add contribution ladder section
  docs/content/en/docs/contribution-guide/contributor-ladder.md
Labels: release-note/docs
