Repository cilium/tetragon, pull requests merged in 2025-08, with the labels that each got.

#3969 lint: Ignore error check for cgroups.DiscoverSubSysIds call
  pkg/sensors/config/confmap/confmap.go
  pkg/testutils/confmap.go
Labels: release-note/misc

#3984 deps: remove direct gopkg.in/yaml.v2 dep
  .golangci.yml
  cmd/tetragon/conf_test.go
  go.mod
  pkg/tracingpolicy/yaml.go
Labels: release-note/misc

#3987 e2e: Remove Cilium related flags
  .github/workflows/run-e2e-tests.yaml
  tests/e2e/flags/flags.go
  tests/e2e/runners/runners.go
  tests/e2e/tests/skeleton/skeleton_test.go
Labels: area/ci, release-note/misc

#4004 contrib: Remove Vagrantfile and related docs
  Vagrantfile
  docs/content/en/docs/contribution-guide/development-setup.md
Labels: release-note/misc

#4013 helm: Quote tetragon.processAncestors.enabled
  install/kubernetes/tetragon/templates/tetragon_configmap.yaml
Labels: release-note/bug

#4011 k8s: Enable k8s control plane for non-k8s deployment
  cmd/tetragon/main.go
  pkg/manager/manager.go
  pkg/option/config.go
  pkg/watcher/crdwatcher/tracingpolicy.go
Labels: release-note/minor

#4008 fix: reject NotifyEnforcer kprobe action without an Enforcer
  pkg/selectors/kernel.go
  pkg/sensors/tracing/generickprobe.go
  pkg/sensors/tracing/policyhandler_linux.go
Labels: area/userspace, release-note/minor

#4029 helm: Add 'containers.extra' helper function
  install/kubernetes/tetragon/templates/_extensions.tpl
  install/kubernetes/tetragon/templates/daemonset.yaml
Labels: release-note/misc

#4027 renovate: sync helm chart version/appVersion update with image tag
  .github/renovate.json5
  install/kubernetes/tetragon/Chart.yaml
Labels: release-note/ci

#4047 tetragon: Make TestUsdtArgs amd64 only
  pkg/sensors/tracing/usdt_amd64_test.go
  pkg/sensors/tracing/usdt_test.go
Labels: release-note/minor

#4048 [backport/v1.5] selectors: Ignore empty matchBinaries
  pkg/selectors/kernel.go
Labels: release-note/backport

#4035 bpf: turn environment configuration storage into a BPF ARRAY storage
  bpf/lib/environ_conf.h
Labels: release-note/minor
