Repository cilium/tetragon, pull requests merged in 2025-07, with the labels that each got.

#3863 tetragon/windows: Fix ancestor list
  pkg/constants/constants_linux.go
  pkg/constants/constants_windows.go
  pkg/pidfile/pid_alive_windows.go
  pkg/pidfile/pid_alive_windows_test.go
  pkg/process/process.go
  pkg/sensors/exec/procevents/proc_reader_windows.go
Labels: release-note/misc

#3868 BTF validation updates
  pkg/btf/validation.go
Labels: release-note/misc

#3827 procevents: fix in-init-tree
  pkg/sensors/exec/procevents/proc_reader.go
  pkg/sensors/exec/procevents/proc_reader_linux.go
  pkg/sensors/exec/procevents/proc_reader_windows.go
Labels: release-note/bug

#3870 fix "security_inode_copy_up" example in docs
  docs/content/en/docs/concepts/tracing-policy/hooks.md
Labels: release-note/docs

#3871 cel: Move heavy operations outside of loops
  pkg/filters/cel_expression.go
Labels: release-note/misc

#3874 Fix CI
  .github/workflows/windows-build-smoke-test.yml
Labels: release-note/ci

#3894 pkg/bpf: explain why LSM attach might fail on arm64 <6.0
  pkg/bpf/detect_linux.go
Labels: release-note/misc

#3888 docs: Clarify export filter scope (JSON vs gRPC)
  docs/content/en/docs/concepts/events.md
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/values.yaml
Labels: release-note/docs

#3895 tracingpolicy: respect syscall attribute in lists
  pkg/sensors/tracing/generickprobe.go
Labels: release-note/bug

#3904 docs: add instruction to cleanup getting started network policy
  docs/content/en/docs/getting-started/network.md
Labels: release-note/docs

#3915 CI: Push OCI Helm chart
  .github/workflows/build-images-ci.yml
  Makefile
Labels: release-note/ci

#3925 bugtool: Collect pprof CPU profile
  .github/workflows/packages-e2e-tests.yaml
  pkg/bugtool/bugtool.go
Labels: kind/backport, release-note/backport

#3924 bugtool: Collect pprof CPU profile
  .github/workflows/packages-e2e-tests.yaml
  pkg/bugtool/bugtool.go
Labels: kind/backport, release-note/backport

#3934 selectors: error on vals larger than supported
  pkg/selectors/kernel.go
Labels: release-note/minor

#3930 feat(helm): add icon section on Chart.yaml file
  install/kubernetes/tetragon/Chart.yaml
Labels: release-note/misc

#3935 fix: Force remove tetragon-clang container for the tetragon-bpf target in case it's still running.
  Makefile
Labels: release-note/misc

#3956 fix: Refactor SIZEOF_EVENT constant to not be a hard-coded value.
  bpf/lib/process.h
Labels: release-note/misc

#3957 Fix a typo in kubectl in the runtime hook documentation
  docs/content/en/docs/installation/runtime-hooks.md
Labels: release-note/docs

#3966 renovate: Remove manual step for cilium/cilium dep
  .github/renovate.json5
Labels: release-note/ci

#3968 ci: Re-enable label checker in ARM
  .github/workflows/run-e2e-tests.yaml
  tests/e2e/tests/labels/labels_test.go
Labels: release-note/ci

#3962 rthooks: Log container ID as a key-value pair
  pkg/policyfilter/rthooks/rthooks.go
Labels: release-note/misc

#3973 Update release template
  .github/ISSUE_TEMPLATE/release_template.md
Labels: release-note/misc
