Repository cilium/tetragon, pull requests merged in 2025-06, with the labels that each got.

#3773 btf: Use user-provided KernelTypes if the btfSpec is nil
  pkg/sensors/program/loader_linux.go
Labels: release-note/misc

#3790 docs: Replace example file for matchCapabilityChanges
  docs/content/en/docs/concepts/tracing-policy/selectors.md
Labels: release-note/docs

#3796 Update selectors.md
  docs/content/en/docs/concepts/tracing-policy/selectors.md
Labels: release-note/docs

#3823 tools: Avoid picking protoc file randomly
  tools/protoc-gen-go-tetragon/common/common.go
  tools/protoc-gen-go-tetragon/eventchecker/eventchecker.go
  tools/protoc-gen-go-tetragon/helpers/helpers.go
  tools/protoc-gen-go-tetragon/types/types.go
Labels: release-note/misc

#3824 helm: fix typo in `metricsLabelFilter` comment
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/values.yaml
Labels: release-note/misc

#3833 Use Go 1.19 atomic types
  .golangci.yml
  go.mod
  go.sum
  pkg/bench/bench.go
  pkg/grpc/exec/exec_test_helper.go
  pkg/policyfilter/k8s_test.go
  pkg/process/cache.go
  pkg/process/process.go
  pkg/ratelimit/ratelimit.go
  pkg/sensors/test/test.go
  vendor/go.uber.org/atomic/.codecov.yml
  vendor/go.uber.org/atomic/.gitignore
  vendor/go.uber.org/atomic/CHANGELOG.md
  vendor/go.uber.org/atomic/LICENSE.txt
  vendor/go.uber.org/atomic/Makefile
  vendor/go.uber.org/atomic/README.md
  vendor/go.uber.org/atomic/bool.go
  vendor/go.uber.org/atomic/bool_ext.go
  vendor/go.uber.org/atomic/doc.go
  vendor/go.uber.org/atomic/duration.go
  vendor/go.uber.org/atomic/duration_ext.go
  vendor/go.uber.org/atomic/error.go
  vendor/go.uber.org/atomic/error_ext.go
  vendor/go.uber.org/atomic/float32.go
  vendor/go.uber.org/atomic/float32_ext.go
  vendor/go.uber.org/atomic/float64.go
  vendor/go.uber.org/atomic/float64_ext.go
  vendor/go.uber.org/atomic/gen.go
  vendor/go.uber.org/atomic/int32.go
  vendor/go.uber.org/atomic/int64.go
  vendor/go.uber.org/atomic/nocmp.go
  vendor/go.uber.org/atomic/pointer_go118.go
  vendor/go.uber.org/atomic/pointer_go118_pre119.go
  vendor/go.uber.org/atomic/pointer_go119.go
  vendor/go.uber.org/atomic/string.go
  vendor/go.uber.org/atomic/string_ext.go
  vendor/go.uber.org/atomic/time.go
  vendor/go.uber.org/atomic/time_ext.go
  vendor/go.uber.org/atomic/uint32.go
  vendor/go.uber.org/atomic/uint64.go
  vendor/go.uber.org/atomic/uintptr.go
  vendor/go.uber.org/atomic/unsafe_pointer.go
  vendor/go.uber.org/atomic/value.go
  vendor/modules.txt
Labels: release-note/misc

#3835 e2e: Make uninstalling Tetragon optional
  tests/e2e/flags/flags.go
  tests/e2e/runners/runners.go
Labels: release-note/ci

#3834 confmap: use config.FindProgramFile()
  pkg/sensors/config/confmap/confmap.go
Labels: release-note/misc

#3832 tetragon/windows: Support multiple programs from a single collection
  pkg/bpf/coll_windows.go
  pkg/sensors/program/loader_windows.go
Labels: release-note/minor

#3842 RFC tetragon: Do not rate limit exit events
  bpf/process/bpf_exit.h
  pkg/testutils/sensors/load.go
Labels: release-note/minor

#3847 tetra: export common.RetryPolicy methods
  cmd/tetra/common/client.go
Labels: release-note/misc

#3849 update cilium/ebpf to v0.19.0
  cmd/tetra/debug/progs.go
  go.mod
  go.sum
  pkg/bugtool/maps.go
  pkg/metrics/kprobemetrics/collector.go
  pkg/sensors/sensors.go
  vendor/github.com/cilium/ebpf/.golangci.yaml
  vendor/github.com/cilium/ebpf/Makefile
  vendor/github.com/cilium/ebpf/README.md
  vendor/github.com/cilium/ebpf/asm/func_lin.go
  vendor/github.com/cilium/ebpf/asm/instruction.go
  vendor/github.com/cilium/ebpf/asm/load_store.go
  vendor/github.com/cilium/ebpf/asm/load_store_string.go
  vendor/github.com/cilium/ebpf/asm/opcode.go
  vendor/github.com/cilium/ebpf/btf/btf.go
  vendor/github.com/cilium/ebpf/btf/btf_types.go
  vendor/github.com/cilium/ebpf/btf/core.go
  vendor/github.com/cilium/ebpf/btf/ext_info.go
  vendor/github.com/cilium/ebpf/btf/format.go
  vendor/github.com/cilium/ebpf/btf/kernel.go
  vendor/github.com/cilium/ebpf/btf/marshal.go
  vendor/github.com/cilium/ebpf/btf/strings.go
  vendor/github.com/cilium/ebpf/btf/types.go
  vendor/github.com/cilium/ebpf/btf/unmarshal.go
  vendor/github.com/cilium/ebpf/collection.go
  vendor/github.com/cilium/ebpf/elf_reader.go
  vendor/github.com/cilium/ebpf/info.go
  vendor/github.com/cilium/ebpf/internal/buffer.go
  vendor/github.com/cilium/ebpf/internal/deque.go
  vendor/github.com/cilium/ebpf/internal/efw/object.go
  vendor/github.com/cilium/ebpf/internal/endian_le.go
  vendor/github.com/cilium/ebpf/internal/epoll/poller.go
  vendor/github.com/cilium/ebpf/internal/kallsyms/kallsyms.go
  vendor/github.com/cilium/ebpf/internal/kallsyms/reader.go
  vendor/github.com/cilium/ebpf/internal/platform/constants.go
  vendor/github.com/cilium/ebpf/internal/platform/platform.go
  vendor/github.com/cilium/ebpf/internal/sys/types.go
  vendor/github.com/cilium/ebpf/internal/sysenc/marshal.go
  vendor/github.com/cilium/ebpf/internal/unix/types_linux.go
  vendor/github.com/cilium/ebpf/internal/unix/types_other.go
  vendor/github.com/cilium/ebpf/internal/version.go
  vendor/github.com/cilium/ebpf/linker.go
  vendor/github.com/cilium/ebpf/map.go
  vendor/github.com/cilium/ebpf/memory.go
  vendor/github.com/cilium/ebpf/memory_unsafe.go
  vendor/github.com/cilium/ebpf/memory_unsafe_tag.go
  vendor/github.com/cilium/ebpf/perf/reader.go
  vendor/github.com/cilium/ebpf/perf/ring.go
  vendor/github.com/cilium/ebpf/pin/pin.go
  vendor/github.com/cilium/ebpf/pin/walk.go
  vendor/github.com/cilium/ebpf/pin/walk_other.go
  vendor/github.com/cilium/ebpf/pin/walk_windows.go
  vendor/github.com/cilium/ebpf/prog.go
  vendor/github.com/cilium/ebpf/syscalls.go
  vendor/github.com/cilium/ebpf/types.go
  vendor/github.com/cilium/ebpf/variable.go
  vendor/modules.txt
Labels: release-note/dependency

#3853 sensor: reduce logs in loading/unloading
  pkg/sensors/load.go
Labels: release-note/minor
