Repository cilium/tetragon, pull requests merged in 2025-02, with the labels that each got.

#3367 docs: fix the Example jq filter in Observability Policies
  docs/content/en/docs/policy-library/observability/_index.md
Labels: area/documentation, release-note/docs

#3366 gitattributes: auto resolve merge conflicts for generated files
  .gitattributes
Labels: release-note/misc

#3383 renovate: Group cel-go together with k8s dependencies
  .github/renovate.json5
Labels: release-note/ci

#3386 workflows: only run build every commit on pull request event
  .github/workflows/static-checks.yaml
Labels: release-note/ci

#3368 api: build using buf
  .github/workflows/generated-files.yaml
  Makefile
  Makefile.defs
  api/Makefile
  api/buf.gen.yaml
  api/buf.yaml
  api/v1/Makefile.protoc
  api/v1/README.md
  api/v1/tetragon/bpf.pb.go
  api/v1/tetragon/bpf.proto
  api/v1/tetragon/capabilities.pb.go
  api/v1/tetragon/capabilities.proto
  api/v1/tetragon/events.pb.go
  api/v1/tetragon/events.pb.json.go
  api/v1/tetragon/events.proto
  api/v1/tetragon/sensors.pb.go
  api/v1/tetragon/sensors.pb.json.go
  api/v1/tetragon/sensors.proto
  api/v1/tetragon/stack.pb.go
  api/v1/tetragon/stack.pb.json.go
  api/v1/tetragon/stack.proto
  api/v1/tetragon/tetragon.pb.go
  api/v1/tetragon/tetragon.pb.json.go
  api/v1/tetragon/tetragon.proto
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/bpf.pb.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/bpf.proto
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/capabilities.pb.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/capabilities.proto
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.json.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.pb.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.pb.json.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.proto
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/stack.pb.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/stack.pb.json.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/stack.proto
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.json.go
  contrib/tetragon-rthooks/vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
  vendor/github.com/cilium/tetragon/api/v1/tetragon/bpf.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/bpf.proto
  vendor/github.com/cilium/tetragon/api/v1/tetragon/capabilities.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/capabilities.proto
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.pb.json.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/events.proto
  vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.pb.json.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors.proto
  vendor/github.com/cilium/tetragon/api/v1/tetragon/stack.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/stack.pb.json.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/stack.proto
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.pb.json.go
  vendor/github.com/cilium/tetragon/api/v1/tetragon/tetragon.proto
Labels: release-note/misc

#3400 cgroups: relax deployment detection logic
  pkg/cgroups/cgroups.go
  pkg/sensors/config/confmap/confmap.go
Labels: release-note/minor

#3401 renovate: more robust parser for Go version in go.mod
  .github/renovate.json5
Labels: area/ci, release-note/ci

#3416 tetragon: Move extract code into separate function
  bpf/process/generic_calls.h
Labels: release-note/minor

#3418 ci: fixes for buf workflow
  .github/workflows/generated-files.yaml
Labels: release-note/misc

#3419 api/Makefile: make it work for worktrees
  api/Makefile
  contrib/scripts/repo-docker-run.sh
Labels: release-note/misc

#3422 pkg/bpf: remove redundant check from HasLSMPrograms
  pkg/bpf/detect.go
  pkg/sensors/tracing/genericlsm.go
Labels: release-note/misc

#3426 filters: Minor CEL refactoring
  pkg/filters/cel_expression.go
Labels: release-note/misc

#3442 helm: Removed default tolerations for the operator
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/values.yaml
Labels: release-note/minor, area/helm

#3449 workflow: fix a bug in build every commit
  .github/workflows/static-checks.yaml
Labels: release-note/ci
