Repository cilium/tetragon, pull requests merged in 2025-03, with the labels that each got.

#3462 syscallmetrics: use syscall type
  pkg/metrics/metricwithpod_test.go
  pkg/metrics/syscallmetrics/syscallmetrics.go
Labels: release-note/misc

#3460 bpf: verification fixes
  bpf/process/generic_calls.h
Labels: release-note/misc

#3466 rthooks: Fix rootDir in createRuntime hook
  contrib/tetragon-rthooks/cmd/oci-hook/main.go
Labels: release-note/minor

#3438 tetra/getevents: add a --reconnect option
  cmd/tetra/getevents/getevents.go
Labels: release-note/misc

#3468 tetra: increase connection timeout to 30s
  cmd/tetra/main.go
Labels: release-note/minor

#3470 docs: fix tracing policy options
  docs/content/en/docs/concepts/tracing-policy/options.md
Labels: release-note/docs

#3439 Use BTF to access skb_ext
  bpf/process/types/skb.h
Labels: release-note/bug

#3472 renovate: add v1.2 for golang 1.23
  .github/renovate.json5
Labels: release-note/minor, release-note/ci

#3489 docs: remove incorrect event types
  docs/content/en/docs/concepts/events.md
Labels: area/documentation, release-note/docs

#3499 install/kubernetes: fix typo
  install/kubernetes/tetragon/templates/tetragon_configmap.yaml
Labels: release-note/misc

#3505 renovate config: automerge more
  .github/renovate.json5
Labels: release-note/ci

#3503 tetragon: Add extra bounds check to extract_arg
  bpf/process/generic_calls.h
Labels: release-note/minor

#3482 helm: Allow extending clusterroles and operator configmap
  install/kubernetes/tetragon/templates/_extensions.tpl
  install/kubernetes/tetragon/templates/clusterrole.yaml
  install/kubernetes/tetragon/templates/operator_clusterrole.yaml
  install/kubernetes/tetragon/templates/operator_configmap.yaml
Labels: release-note/minor, area/helm

#3512 pkg/bpf: mount securityfs to check lsm bpf
  pkg/bpf/detect_linux.go
Labels: release-note/minor

#3524 main: Split k8s watchers into process metadata and policy
  cmd/tetragon/main_linux.go
  pkg/watcher/watcher.go
Labels: kind/bug, release-note/misc

#3443 Added support to run multiple Tetragon operator replicas simultaneously
  contrib/upgrade-notes/latest.md
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/templates/operator_configmap.yaml
  install/kubernetes/tetragon/templates/operator_deployment.yaml
  install/kubernetes/tetragon/templates/operator_role.yaml
  install/kubernetes/tetragon/templates/operator_rolebinding.yaml
  install/kubernetes/tetragon/values.yaml
  operator/cmd/serve/serve.go
  operator/option/config.go
Labels: kind/enhancement, release-note/minor, area/helm

#3545 Prepare for v1.4.0 release
  contrib/upgrade-notes/latest.md
  contrib/upgrade-notes/v1.4.0.md
  docs/config/_default/hugo.toml
  docs/content/en/docs/reference/helm-chart.md
  install/kubernetes/tetragon/Chart.yaml
  install/kubernetes/tetragon/README.md
  install/kubernetes/tetragon/values.yaml
Labels: release-note/misc

#3548 tetragon/windows: Port reader/namespace package to Windows
  pkg/reader/namespace/namespace_linux.go
  pkg/reader/namespace/namespace_windows.go
Labels: release-note/minor

#3534 tetragon/windows: Port package errmetrics to Windows
  pkg/errmetrics/err_msg_windows.go
  pkg/errmetrics/err_msg_windows_test.go
Labels: release-note/minor

#3530 tetragon/windows: Compilation only change for pkg/metrics/syscallmetrics
  pkg/metrics/syscallmetrics/raw_syscall_name_windows.go
Labels: release-note/minor

#3551 [v1.2] watcher: Fix pod lookup if the index is out-of-sync
  pkg/watcher/fake.go
  pkg/watcher/watcher.go
Labels: kind/backport, release-note/bug

#3529 tetragon/windows: Port pkg/kernels to Windows
  pkg/kernels/kernels.go
  pkg/kernels/kernels_common.go
  pkg/kernels/kernels_windows.go
Labels: release-note/minor

#3536 tetragon/windows: Compilation only change to compile cgroups package
  pkg/cgroups/cgroups.go
  pkg/cgroups/cgroups_linux.go
  pkg/cgroups/cgroups_windows.go
Labels: release-note/minor

#3555 e2e: port forwarding fixes
  pkg/multiplexer/multiplexer.go
  tests/e2e/checker/rpcchecker.go
  tests/e2e/helpers/grpc/grpc.go
  tests/e2e/helpers/portforward.go
  tests/e2e/state/state.go
Labels: area/ci, release-note/ci, needs-backport/1.2, needs-backport/1.3, needs-backport/1.4

#3532 tetragon/windows: Port pidfile package on Windows
  pkg/pidfile/pid_alive_linux.go
  pkg/pidfile/pid_alive_windows.go
  pkg/pidfile/pidfile.go
  pkg/pidfile/pidfile_test.go
Labels: release-note/minor

#3533 tetragon/windows: Compilation only Change for pkg/procsyms on Windows
  pkg/procsyms/procsyms.go
  pkg/procsyms/procsyms_linux.go
  pkg/procsyms/procsyms_windows.go
Labels: release-note/minor

#3531 tetragon/windows: Compilation only change for pkg/metricconfig package on Windows
  pkg/metricsconfig/healthmetrics.go
  pkg/metricsconfig/healthmetrics_linux.go
  pkg/metricsconfig/healthmetrics_windows.go
Labels: release-note/minor

#3557 v1.4 backports 20250326
  pkg/multiplexer/multiplexer.go
  tests/e2e/checker/rpcchecker.go
  tests/e2e/helpers/grpc/grpc.go
  tests/e2e/helpers/portforward.go
  tests/e2e/state/state.go
Labels: release-note/ci

#3564 v1.3 backports
  pkg/multiplexer/multiplexer.go
  tests/e2e/checker/rpcchecker.go
  tests/e2e/helpers/grpc/grpc.go
  tests/e2e/helpers/portforward.go
  tests/e2e/state/state.go
Labels: release-note/ci

#3566 helm: rthooks: fix extraHookArgs
  install/kubernetes/tetragon/templates/_container_rthooks.tpl
Labels: release-note/bug, needs-backport/1.2, needs-backport/1.3, needs-backport/1.4

#3569 1.4 backports
  install/kubernetes/tetragon/templates/_container_rthooks.tpl
Labels: release-note/backport

#3562 tetragon/windows: Use a package-level 'not supported' error variable
  pkg/cgroups/cgroups_windows.go
  pkg/constants/constants_windows.go
  pkg/sensors/tracing/lists_windows.go
  pkg/sensors/tracing/policyhandler_windows.go
Labels: kind/cleanup, release-note/misc

#3561 tetragon/windows: port package sensors/exec/procevents into Windows
  pkg/sensors/exec/procevents/proc.go
  pkg/sensors/exec/procevents/proc_linux.go
  pkg/sensors/exec/procevents/proc_reader.go
  pkg/sensors/exec/procevents/proc_reader_linux.go
  pkg/sensors/exec/procevents/proc_reader_windows.go
  pkg/sensors/exec/procevents/proc_windows.go
  pkg/sensors/exec/userinfo/userinfo_test.go
Labels: release-note/minor
